In [1]:
import requests
import os
from dotenv import load_dotenv
import json
import pandas as pd

## Calling the API

In [2]:
load_dotenv()
API_KEY =  os.getenv("API_KEY")

Base URL for getting any data from the API

In [3]:
base_url = "https://backend.simfin.com/api/v3/companies"


headers = {"accept": "application/json",
            "Authorization": f"{API_KEY}"}

### Getting a list of all tickers

In [4]:
endpoint_url = f"{base_url}/list"

list_response = requests.get(endpoint_url, headers=headers)

if list_response.status_code == 200:
    # Parse the JSON response
    list_data = list_response.json()
else:
    print(f"Failed to retrieve data. Status code: {list_response.status_code}")

#This line of code below is just an example to make sure everything works
list_data[0]

{'id': 1234791,
 'name': 'STERLING BANCORP',
 'ticker': 'STL',
 'sectorCode': 104002,
 'industryName': 'Financial Services',
 'sectorName': 'Banks',
 'isin': 'US85917A1007'}

In [5]:
#This gets a list of all the tickers
tickers= []
for i in list_data:
    tickers.append([i['ticker'], i['name']] )

print(tickers)

[['STL', 'STERLING BANCORP'], ['NSU', 'NEVSUN RESOURCES LTD'], ['PINX:ICNAF', 'Icanic Brands Co Inc.'], ['INFY', 'Infosys Ltd'], ['XLRN', 'ACCELERON PHARMA INC'], ['ITEM4', 'AXA S.A.'], ['NWY', 'New York & Company, Inc.'], ['ACAT', 'ARCTIC CAT INC'], ['VRTU', 'VIRTUSA CORP'], ['APIC', 'Apigee Corp'], ['LABL', 'MULTI COLOR Corp'], ['ASNA', 'Ascena Retail Group, Inc.'], ['ABAX', 'ABAXIS INC'], ['CK00015847', 'TOPS HOLDING II CORP'], ['JOY', 'JOY GLOBAL INC'], ['SHOS', 'SEARS HOMETOWN & OUTLET STORES, INC.'], ['SSI', 'STAGE STORES INC'], ['CST', 'CST BRANDS, INC.'], ['COVS', 'Covisint Corp'], ['SMRT_delisted', 'STEIN MART INC'], ['LAYN', 'LAYNE CHRISTENSEN CO'], ['KKD', 'KRISPY KREME DOUGHNUTS INC'], ['NMBL', 'Nimble Storage Inc'], ['MIK', 'Michaels Companies, Inc.'], ['ARRY_delisted', 'ARRAY BIOPHARMA INC'], ['KMG', 'KMG CHEMICALS INC'], ['FRED', 'FREDS INC'], ['CMD', 'CANTEL MEDICAL CORP'], ['SYUT', 'Synutra International, Inc.'], ['RAX', 'RACKSPACE HOSTING, INC.'], ['MFRM', 'MATTRESS FIRM HOLDING CORP.'], ['MGCD', 'MGC DIAGNOSTICS Corp'], ['EEI', 'ECOLOGY & ENVIRONMENT INC'], ['CLC', 'CLARCOR INC.'], ['BV_old', 'Bazaarvoice Inc'], ['ARTEC', 'Artec Global Media, Inc.'], ['AGN', 'Allergan plc'], ['AET', 'AETNA INC /PA/'], ['FUEL', 'Rocket Fuel Inc.'], ['BREW', 'CRAFT BREW ALLIANCE, INC.'], ['INFOR', 'Infor, Inc.'], ['WSCI', 'WSI INDUSTRIES, INC.'], ['ALXN', 'ALEXION PHARMACEUTICALS INC'], ['APC', 'ANADARKO PETROLEUM CORP'], ['SLNM', 'SALON MEDIA GROUP INC'], ['BCR', 'BARD C R INC /NJ/'], ['KITE', 'Kite Pharma, Inc.'], ['EIGI', 'Endurance International Group Holdings, Inc.'], ['REMI', 'REMEDENT, INC.'], ['DTRM', 'DETERMINE, INC.'], ['QLGC', 'QLOGIC CORP'], ['COR_delisted', 'CoreSite Realty Corp'], ['BOJA', "Bojangles', Inc."], ['ARA', 'American Renal Associates Holdings, Inc.'], ['GLUU', 'GLU MOBILE INC'], ['SNAK', 'INVENTURE FOODS, INC.'], ['SWY', 'SAFEWAY INC'], ['WFM', 'WHOLE FOODS MARKET INC'], ['WTMK', 'WHITEMARK HOMES INC'], ['P', 'Pandora Media, Inc.'], ['ARO', 'AEROPOSTALE INC'], ['RHT', 'RED HAT INC'], ['ACPW', 'ACTIVE POWER INC'], ['PRTX', 'PROTALEX INC'], ['MYCC', 'ClubCorp Holdings, Inc.'], ['KLXI', 'KLX Inc.'], ['CALD', 'CALLIDUS SOFTWARE INC'], ['GTT', 'GTT Communications, Inc.'], ['CBM', 'CAMBREX CORP'], ['CBKCQ', 'CHRISTOPHER & BANKS CORP'], ['DNKN', "DUNKIN' BRANDS GROUP, INC."], ['WBC', 'WABCO Holdings Inc.'], ['MIXX', 'MIX 1 LIFE, INC.'], ['IVTY', 'Invuity, Inc.'], ['ESRX', 'Express Scripts Holding Co.'], ['MJCO', 'Majesco'], ['CBI', 'CHICAGO BRIDGE & IRON CO N V'], ['CPN', 'CALPINE CORP'], ['HOT', 'STARWOOD HOTEL & RESORTS WORLDWIDE, INC'], ['SPNC', 'SPECTRANETICS CORP'], ['ESI_delisted', 'ITT EDUCATIONAL SERVICES INC'], ['SFS', 'Smart & Final Stores, Inc.'], ['CHSP', 'Chesapeake Lodging Trust'], ['WCIC', 'WCI Communities, Inc.'], ['MOBL', 'MOBILEIRON, INC.'], ['ADPT_delisted', 'Adeptus Health Inc.'], ['TWX', 'TIME WARNER INC.'], ['TST', 'THESTREET, INC.'], ['NFX', 'NEWFIELD EXPLORATION CO /DE/'], ['SGY', 'STONE ENERGY CORP'], ['OXFD', 'Oxford Immunotec Global PLC'], ['SGM', 'STONEGATE MORTGAGE CORP'], ['GRA', 'W R GRACE & CO'], ['IBKC', 'IBERIABANK CORP'], ['SEV', 'SEVCON, INC.'], ['IMPV', 'IMPERVA INC'], ['SHPGF', 'Shire plc'], ['GUID', 'Guidance Software, Inc.'], ['OZRK', 'BANK OF THE OZARKS INC'], ['BID', 'SOTHEBYS'], ['SQBG', 'Sequential Brands Group, Inc.'], ['NATL', 'National Interstate CORP'], ['SOHU', 'SOHU COM INC'], ['ALR', 'ALERE INC.'], ['RATE', 'Bankrate, Inc.'], ['TESO', 'TESCO CORP'], ['ITG', 'INVESTMENT TECHNOLOGY GROUP, INC.'], ['CALL', 'MAGICJACK VOCALTEC LTD'], ['CNXR', 'CONNECTURE INC'], ['GIDYL', 'GI DYNAMICS, INC.'], ['COTV', 'Cotiviti Holdings, Inc.'], ['MXPT', 'MaxPoint Interactive, Inc.'], ['LOV', 'SPARK NETWORKS INC'], ['FCS', 'FAIRCHILD SEMICONDUCTOR INTERNATIONAL INC'], ['RLOC', 'ReachLocal Inc'], ['STFR', 'Steadfast Apartment REIT, Inc.'], ['MXIM', 'MAXIM INTEGRATED PRODUCTS INC'], ['BVSN', 'BROADVISION INC'], ['DDE', 'DOVER DOWNS GAMING & ENTERTAINMENT INC'], ['USMD', 'USMD Holdings, Inc.'], ['NEOS', 'Neos Therapeutics, Inc.'], ['CCFI', 'Community Choice Financial Inc.'], ['CIK0001446', 'Macquarie Equipment Leasing Fund, LLC'], ['ICPW', 'IRONCLAD PERFORMANCE WEAR CORP'], ['HPJ', 'Highpower International, Inc.'], ['SPAN', 'SPAN AMERICA MEDICAL SYSTEMS INC'], ['SPLS', 'STAPLES INC'], ['PRGB', 'Protea Biosciences Group, Inc.'], ['CK00015317', 'Shea Homes Limited Partnership'], ['LTRX', 'LANTRONIX INC'], ['DESTQ', 'Destination Maternity Corp'], ['TIVO', 'TIVO INC'], ['EXA', 'EXA CORP'], ['LLTC', 'LINEAR TECHNOLOGY CORP /CA/'], ['WOLF', 'WOLFSPEED, INC.'], ['JCP', 'J C PENNEY CO INC'], ['MENT', 'MENTOR GRAPHICS CORP'], ['JCG', 'J CREW GROUP INC'], ['TECD', 'TECH DATA CORP'], ['BRCD', 'BROCADE COMMUNICATIONS SYSTEMS INC'], ['SCG', 'SCANA CORP'], ['ACET_delisted', 'ACETO CORP'], ['AKRX', 'AKORN INC'], ['GMAN', 'Gordmans Stores, Inc.'], ['FNSR', 'FINISAR CORP'], ['EV', 'EATON VANCE CORP'], ['BONT', 'BON TON STORES INC'], ['VAL_delisted', 'VALSPAR CORP'], ['SIGM', 'SIGMA DESIGNS INC'], ['SHLO', 'SHILOH INDUSTRIES INC'], ['FRANQ', "Francesca's Holdings CORP"], ['SNOW_delisted', 'Intrawest Resorts Holdings, Inc.'], ['NAV', 'NAVISTAR INTERNATIONAL CORP'], ['CNNX', 'CONE Midstream Partners LP'], ['PERF', 'Perfumania Holdings, Inc.'], ['AEPI', 'AEP INDUSTRIES INC'], ['PRXL', 'PAREXEL INTERNATIONAL CORP'], ['PRCP', 'PERCEPTRON INC/MI'], ['NCSO', '99 CENTS ONLY STORES LLC'], ['HDS', 'HD Supply Holdings, Inc.'], ['CSC', 'COMPUTER SCIENCES CORP'], ['CK00015503', 'BakerCorp International, Inc.'], ['SHOR', 'ShoreTel Inc'], ['PTI', 'Patheon N.V.'], ['HOME', 'At Home Group Inc.'], ['CHKE', 'CHEROKEE INC'], ['NRTHF', 'Northern Power Systems Corp.'], ['RP', 'REALPAGE INC'], ['PIR', 'PIER 1 IMPORTS INC/DE'], ['XCRA', 'Xcerra Corp'], ['TIF', 'TIFFANY & CO'], ['NBL', 'NOBLE ENERGY INC'], ['IDSY', 'ID SYSTEMS INC'], ['RDC', 'ROWAN COMPANIES PLC'], ['GIMO', 'Gigamon Inc.'], ['BLOX', 'INFOBLOX INC'], ['BGG', 'BRIGGS & STRATTON CORP'], ['MDP', 'MEREDITH CORP'], ['RDEN', 'ELIZABETH ARDEN INC'], ['BRS', 'Bristow Group Inc'], ['PHH', 'PHH CORP'], ['YHOO', 'YAHOO INC'], ['BRCM', 'BROADCOM CORP'], ['EMC', 'EMC CORP'], ['CA_delisted', 'CA, INC.'], ['MAMS', 'MAM SOFTWARE GROUP, INC.'], ['DDMG', 'Digital Domain Media Group, Inc.'], ['EGLT', 'Egalet Corp'], ['BWLA', 'BOWL AMERICA INC'], ['ZINCQ', 'Horsehead Holding Corp'], ['AXN', 'AOXING PHARMACEUTICAL COMPANY, INC.'], ['RT', 'RUBY TUESDAY INC'], ['INFO', 'IHS Markit Ltd.'], ['SSNI', 'SILVER SPRING NETWORKS INC'], ['MYL', 'Mylan N.V.'], ['CIT', 'CIT GROUP INC'], ['STI', 'SUNTRUST BANKS INC'], ['RAI', 'REYNOLDS AMERICAN INC'], ['BLUD', 'IMMUCOR INC'], ['PVHO', 'Provision Holding, Inc.'], ['IMSCQ', 'IMPLANT SCIENCES CORP'], ['RSYS', 'RADISYS CORP'], ['SONC', 'SONIC CORP'], ['ALJ', 'Alon USA Energy, Inc.'], ['TYPE', 'Monotype Imaging Holdings Inc.'], ['MIC', 'Macquarie Infrastructure Corp'], ['NTRI', 'NUTRI SYSTEM INC /DE/'], ['TSRO', 'TESARO, Inc.'], ['DPLO', 'Diplomat Pharmacy, Inc.'], ['KTWO', 'K2M GROUP HOLDINGS, INC.'], ['IRG', 'Ignite Restaurant Group, Inc.'], ['BBRG', 'Bravo Brio Restaurant Group, Inc.'], ['S_delisted', 'SPRINT Corp'], ['ACIA', 'Acacia Communications, Inc.'], ['RTN', 'RAYTHEON CO/'], ['ININ', 'Interactive Intelligence Group, Inc.'], ['ISIL', 'INTERSIL CORP/DE'], ['QCP', 'QUALITY CARE PROPERTIES, INC.'], ['AMTD', 'TD AMERITRADE HOLDING CORP'], ['HRC', 'Hill-Rom Holdings, Inc.'], ['NUTR', 'NUTRACEUTICAL INTERNATIONAL CORP'], ['ABCD', 'CAMBIUM LEARNING GROUP, INC.'], ['KRFT', 'Kraft Foods Group, Inc.'], ['WAIR', 'Wesco Aircraft Holdings, Inc'], ['VAR', 'VARIAN MEDICAL SYSTEMS INC'], ['MSCC', 'MICROSEMI CORP'], ['FLUG', 'FLURIDA GROUP INC'], ['JMBA', 'JAMBA, INC.'], ['FLIR', 'FLIR SYSTEMS INC'], ['KTEC_delisted', 'KEY TECHNOLOGY INC'], ['CK00007861', 'GYMBOREE CORP'], ['ULTI', 'ULTIMATE SOFTWARE GROUP INC'], ['VSM', 'Versum Materials, Inc.'], ['XEC', 'Cimarex Energy'], ['CXO', 'Concho Resources'], ['CSRA', 'CSRA Inc.'], ['ETFC', 'E*Trade'], ['ENDP_old', 'Endo International'], ['FTI_old', 'FMC Technologies Inc.'], ['GGP_old', 'General Growth Properties Inc.'], ['HAR', "Harman Int'l Industries"], ['LLL', 'L-3 Communications Holdings'], ['MJN', 'Mead Johnson'], ['MDT_old', 'Medtronic INC'], ['MYL_old', 'Mylan N.V.'], ['COL', 'Rockwell Collins'], ['SNI', 'Scripps Networks Interactive Inc.'], ['STJ', 'St Jude Medical'], ['ANDV', 'Andeavor'], ['TSS', 'Total System Services'], ['VIA', 'Viacom Inc.'], ['FPRX', 'FIVE PRIME THERAPEUTICS INC'], ['XLNX', 'XILINX INC'], ['CELG', 'CELGENE CORP /DE/'], ['PNRA', 'PANERA BREAD CO'], ['ATW', 'ATWOOD OCEANICS INC'], ['CPXX', 'Celator Pharmaceuticals Inc'], ['HPTX', 'HYPERION THERAPEUTICS INC'], ['PCP', 'PRECISION CASTPARTS CORP'], ['KATE', 'Kate Spade & Co'], ['AGN_old', 'Allergan Inc.'], ['ALTR_delisted', 'Altera Corp.'], ['ARG', 'Airgas, Inc.'], ['GGP', 'General Growth Properties, Inc'], ['GHML', 'Gold Hills Mining LTD'], ['ARRS', 'Arris Group Inc'], ['CAVM', 'Cavium Inc'], ['DFT', 'Dupont Fabros Technology Inc'], ['ELLI', 'Ellie Mae Inc'], ['GWR', 'Genesee & Wyoming Inc'], ['GXP', 'Great Plains Energy Inc'], ['MBFI', 'MB Financial Inc'], ['NUAN', 'Nuance Communications Inc'], ['RSPP', 'RSP Permian Inc'], ['STAY', 'Extended Stay America Inc'], ['USG', 'Usg Corp'], ['VNTV', 'Vantiv Inc'], ['WFT_old', 'Weatherford International LTD'], ['WGL', 'WGL Holdings Inc'], ['WPX', 'WPX Energy Inc'], ['WRI', 'Weingarten Realty Investors'], ['XCO', 'EXCO RESOURCES INC'], ['RGC', 'Regal Entertainment Group'], ['CSLT', 'CASTLIGHT HEALTH, INC.'], ['ATHN_delisted', 'ATHENAHEALTH INC'], ['MDSO', 'Medidata Solutions, Inc.'], ['INOV', 'Inovalon Holdings, Inc.'], ['QEP', 'QEP RESOURCES, INC.'], ['SNDK', 'SANDISK CORP'], ['MWW', 'MONSTER WORLDWIDE, INC.'], ['TOY_delisted', 'TOYS R US INC'], ['KND', 'KINDRED HEALTHCARE, INC'], ['CLCT', 'COLLECTORS UNIVERSE INC'], ['FDC', 'FIRST DATA CORP'], ['CNVR', 'CONVERSANT, INC.'], ['CY', 'CYPRESS SEMICONDUCTOR CORP /DE/'], ['CDI', 'CDI CORP'], ['PDLI', 'PDL BIOPHARMA, INC.'], ['SPRT', 'Support.com, Inc.'], ['CRR', 'CARBO CERAMICS INC'], ['VER', 'VEREIT, Inc.'], ['WMAR', 'WEST MARINE INC'], ['ERS', 'EMPIRE RESOURCES INC /NEW/'], ['BSPM', 'Biostar Pharmaceuticals, Inc.'], ['SORL', 'SORL Auto Parts Inc'], ['CIE', 'Cobalt International Energy, Inc.'], ['ETEC', 'EMTEC INC/NJ'], ['DGTC', 'DGT Holdings Corp.'], ['BRRE', 'BLUE RIDGE REAL ESTATE CO'], ['EEP', 'ENBRIDGE ENERGY PARTNERS LP'], ['AUDH', 'AURORA DIAGNOSTICS HOLDINGS LLC'], ['SNGC', 'SOUTHERN NATURAL GAS COMPANY, L.L.C.'], ['WLB', 'WESTMORELAND COAL Co'], ['OA', 'ORBITAL ATK, INC.'], ['IPXL', 'IMPAX LABORATORIES INC'], ['TOWR', 'Tower International, Inc.'], ['TVPT', 'Travelport Worldwide LTD'], ['WIN', 'WINDSTREAM HOLDINGS, INC.'], ['TPCO', 'Tribune Publishing Co'], ['CRZO', 'CARRIZO OIL & GAS INC'], ['GPT', 'Gramercy Property Trust'], ['REN', 'Resolute Energy Corp'], ['MDR', 'MCDERMOTT INTERNATIONAL INC'], ['HABT', 'Habit Restaurants, Inc.'], ['LINE', 'LINN ENERGY, INC.'], ['KEM', 'KEMET CORP'], ['LOGM', 'LogMeIn, Inc.'], ['FIT', 'FITBIT INC'], ['FMSA', 'FAIRMOUNT SANTROL HOLDINGS INC.'], ['GASE', 'GASE ENERGY, INC.'], ['CICC', 'China Internet Cafe Holdings Group, Inc.'], ['GPCM', 'GRANDPARENTS.COM, INC.'], ['WBMD', 'WebMD Health Corp.'], ['TLRA', 'Telaria, Inc.'], ['HOMR', 'STEVVA Corp'], ['STMP', 'STAMPS.COM INC'], ['SFLY', 'SHUTTERFLY INC'], ['LEXE', 'Liberty Expedia Holdings, Inc.'], ['TRCO', 'TRIBUNE MEDIA CO'], ['WIFI', 'BOINGO WIRELESS INC'], ['WEB', 'WEB.COM GROUP, INC.'], ['CETV', 'CENTRAL EUROPEAN MEDIA ENTERPRISES LTD'], ['XOXO', 'XO GROUP INC.'], ['LEAF', 'LEAF GROUP LTD.'], ['MEET', 'Meet Group, Inc.'], ['NLN', 'NEULION, INC.'], ['CIK0001536', 'iVoiceIdeas, Inc.'], ['RLJE', 'RLJ ENTERTAINMENT, INC.'], ['MNI', 'MCCLATCHY CO'], ['NDMT', 'NowNews Digital Media Technology Co. Ltd.'], ['EMMS', 'EMMIS COMMUNICATIONS CORP'], ['GSEG', 'SATYA WORLDWIDE, INC.'], ['SDDL', 'DTHERA SCIENCES'], ['CTOP', 'Ceetop Inc.'], ['DEVV', 'BIOSCIENCE NEUTRACEUTICALS INC'], ['AMRU', 'AMARU INC'], ['VAPE', 'Vape Holdings, Inc.'], ['ITNM', 'INTERNATIONAL MONETARY SYSTEMS LTD /WI/'], ['JINM', 'One2one Living Corp'], ['RJDG', 'RJD Green, Inc.'], ['MJTK', 'CANNASYS INC'], ['IDLM', 'Idle Media, Inc.'], ['MMEG', 'MOMENTOUS ENTERTAINMENT GROUP INC'], ['YITD', 'Yinhang Internet Technologies Development, Inc.'], ['EWRX', 'DLD Group, Inc.'], ['GNZR', 'Generation Zero Group, Inc.'], ['SANP', 'SANTO MINING CORP.'], ['SEEK', 'THEDIRECTORY.COM, INC.'], ['REDG', 'Red Giant Entertainment, Inc.'], ['CHAA', 'chatAND, Inc.'], ['IMMC', 'Stop Sleep Go Inc.'], ['PEDH', 'PEOPLES EDUCATIONAL HOLDINGS'], ['CWRL', 'Cornerworld Corp'], ['MEDF', 'Medifirst Solutions, Inc.'], ['GOBK', 'GLOBALINK, LTD.'], ['XHUA', 'XINHUA CHINA LTD'], ['VIDA', 'VIDAROO Corp'], ['XING', 'China Xingbang Industry Group Inc.'], ['AJBI', 'AMI JAMES BRANDS, INC.'], ['MENI', 'Mobilized Entertainment, Inc.'], ['STTK', 'Total Sports Media, Inc.'], ['IDDR', 'IDdriven, Inc.'], ['ADTM', 'Adaptive Medias, Inc.'], ['RAVN', 'RAVEN INDUSTRIES INC'], ['CYNK', 'Cynk Technology Corp.'], ['GEPC', 'Gepco, Ltd.'], ['MSHF', 'MediaShift, Inc.'], ['BABL', 'Buildablock Corp.'], ['BFLD', 'BROADCAST LIVE DIGITAL CORP.'], ['LOCMQ', 'LOCAL Corp'], ['EFCT', 'EFACTOR GROUP CORP.'], ['SAAX', 'NOUVEAU VENTURES INC.'], ['MECK', 'Mecklermedia Corp'], ['IMTV', 'Imagination TV, Inc.'], ['FLWD', 'FileWarden.com'], ['CIK1479320', 'Vibe Ventures Inc.'], ['OMGB', 'OMEGA BRANDS INC.'], ['OURN', 'Ournett Holdings, Inc.'], ['PTRR', 'WEI PAI ELECTRONIC COMMERCE CO., LTD.'], ['CMND', 'Clearmind Medicine Inc.'], ['DMDW', 'DOMAIN MEDIA CORP'], ['CK00011568', 'INTELSAT INVESTMENTS S.A.'], ['IHC', 'INDEPENDENCE HOLDING CO'], ['GDI', 'GARDNER DENVER INC'], ['CKP', 'CHECKPOINT SYSTEMS INC'], ['BPL', 'BUCKEYE PARTNERS, L.P.'], ['HDP', 'Hortonworks, Inc.'], ['ACW', 'ACCURIDE CORP'], ['AKS', 'AK STEEL HOLDING CORP'], ['SHLM', 'SCHULMAN A INC'], ['ARCW', 'ARC Group Worldwide, Inc.'], ['FNJN', 'FINJAN HOLDINGS, INC.'], ['SVU', 'SUPERVALU INC'], ['MCF', 'CONTANGO OIL & GAS CO'], ['BMS', 'BEMIS CO INC'], ['INBI', 'Infusion Brands International, Inc.'], ['WPTH', 'Westport Energy Holdings Inc.'], ['CYNX', 'CelLynx Group, Inc.'], ['QSIM', 'QUANTUMSPHERE, INC.'], ['RELY', 'Elah Holdings, Inc.'], ['SIAL', 'SIGMA ALDRICH CORP'], ['HCOM', 'Hawaiian Telcom Holdco, Inc.'], ['FSBI', 'FIDELITY BANCORP INC'], ['LION', 'FIDELITY SOUTHERN CORP'], ['CMRO', 'COMARCO INC'], ['SYNT', 'SYNTEL INC'], ['TIS', 'Orchids Paper Products CO /DE'], ['ZAYO', 'Zayo Group Holdings, Inc.'], ['MB', 'MINDBODY, Inc.'], ['PS', 'Pluralsight, Inc.'], ['HMNY', 'Helios & Matheson Analytics Inc.'], ['UPL', 'ULTRA PETROLEUM CORP'], ['CSS', 'CSS INDUSTRIES INC'], ['IMMY', 'Imprimis Pharmaceuticals, Inc.'], ['DYN_delisted', 'DYNEGY INC.'], ['GLBL_delisted', 'TERRAFORM GLOBAL, INC.'], ['CQH', 'Cheniere Energy Partners LP Holdings, LLC'], ['WDHR', 'WeedHire International, Inc.'], ['OVATION', 'Weed Growth Fund, Inc.'], ['BRCK', 'BlackRock Global Horizons I L.P.'], ['NOIZ', 'MICRONETICS INC'], ['CNXT', 'CONEXANT SYSTEMS INC'], ['UNS', 'UNS Energy Corp'], ['ASCMA', 'Ascent Capital Group, Inc.'], ['HEMA', 'HEMACARE CORP /CA/'], ['TERP', 'TerraForm Power, Inc.'], ['PEGI', 'Pattern Energy Group Inc.'], ['HTM', 'US GEOTHERMAL INC'], ['FRP', 'FAIRPOINT COMMUNICATIONS INC'], ['DATA', 'Tableau Software Inc'], ['EPE', 'EP Energy Corp'], ['JDAS', 'JDA SOFTWARE GROUP INC'], ['WLT', 'Walter Energy, Inc.'], ['APU', 'AMERIGAS PARTNERS LP'], ['CUB', 'CUBIC CORP /DE/'], ['ESC', 'EMERITUS CORP\\WA\\'], ['SRZ', 'SUNRISE SENIOR LIVING INC'], ['CHDX', 'CHINDEX INTERNATIONAL INC'], ['SEMG', 'SemGroup Corp'], ['QTNA', 'QUANTENNA COMMUNICATIONS INC'], ['XSPY', 'Spy Inc.'], ['ARTX', 'AROTECH CORP'], ['APTI', 'Apptio Inc'], ['WCG', 'WELLCARE HEALTH PLANS, INC.'], ['CSOD', 'Cornerstone OnDemand Inc'], ['BNCL', 'Beneficial Bancorp Inc.'], ['LXRP', 'Lexaria Bioscience Corp.'], ['PE', 'Parsley Energy, Inc.'], ['MXWL', 'MAXWELL TECHNOLOGIES INC'], ['ESL', 'ESTERLINE TECHNOLOGIES CORP'], ['ECYT', 'ENDOCYTE INC'], ['BKS', 'BARNES & NOBLE INC'], ['AHFD', 'Active Health Foods, Inc.'], ['GHDX', 'GENOMIC HEALTH INC'], ['BRSS', 'GLOBAL BRASS & COPPER HOLDINGS, INC.'], ['CMBG', 'Cellular Biomedicine Group, Inc.'], ['LOXO', 'Loxo Oncology, Inc.'], ['SYRG', 'SRC Energy Inc.'], ['ODT', 'Odonate Therapeutics, Inc.'], ['RSLS', 'ReShape Lifesciences Inc.'], ['LGCY', 'Legacy Reserves Inc.'], ['PGNX', 'PROGENICS PHARMACEUTICALS INC'], ['ARQL', 'ARQULE INC'], ['STML', 'STEMLINE THERAPEUTICS INC'], ['KFN', 'KKR Financial Holdings LLC'], ['ALTMS', 'Alta Mesa Holdings, LP'], ['IMDZ', 'IMMUNE DESIGN CORP.'], ['VSLR', 'Vivint Solar, Inc.'], ['EVHC', 'Envision Healthcare Corp'], ['ENZB', 'EnzymeBioSystems'], ['OMED', 'OncoMed Pharmaceuticals Inc'], ['USCR', 'US CONCRETE INC'], ['WSTC', 'WEST CORP'], ['CVA', 'COVANTA HOLDING CORP'], ['AFSI', 'Amtrust Financial Services, Inc.'], ['BSTC', 'BIOSPECIFICS TECHNOLOGIES CORP'], ['XONE', 'ExOne Co'], ['DFODQ', 'DEAN FOODS CO'], ['YOGAQ', 'YogaWorks, Inc.'], ['GAMZ', 'Gamzio Mobile, Inc.'], ['CCE', 'COCA-COLA REFRESHMENTS USA, INC.'], ['VLRX', 'Valeritas Holdings Inc.'], ['FRSH', "Papa Murphy's Holdings, Inc."], ['KONAQ', 'KONA GRILL INC'], ['CUO', 'CONTINENTAL MATERIALS CORP'], ['IOTS', 'ADESTO TECHNOLOGIES Corp'], ['CLDR', 'Cloudera, Inc.'], ['SMA', 'Symmetry Medical Inc.'], ['CLGX', 'CORELOGIC, INC.'], ['CBLK', 'Carbon Black, Inc.'], ['FSCT', 'FORESCOUT TECHNOLOGIES, INC'], ['C649', 'Dialogic Inc.'], ['PCMI', 'PCM, INC.'], ['ALSK', 'ALASKA COMMUNICATIONS SYSTEMS GROUP INC'], ['SQBK', 'SQUARE 1 FINANCIAL INC'], ['XLGROUP', 'XL GROUP LTD'], ['ZAGG', 'ZAGG Inc'], ['ANDX', 'ANDEAVOR LOGISTICS LP'], ['KYAK', 'KAYAK Software Corp'], ['OMP', 'Oasis Midstream Partners LP'], ['AREX', 'Approach Resources Inc'], ['WMGI_delisted', 'Wright Medical Group N.V.'], ['NGHC', 'National General Holdings Corp.'], ['IPHI', 'INPHI Corp'], ['TLND', 'Talend SA'], ['DLPH', 'Delphi Technologies PLC'], ['TEP', 'Tallgrass Energy Partners, LP'], ['TLRD', 'TAILORED BRANDS INC'], ['CWBS', 'COMMONWEALTH BANKSHARES INC'], ['DRI.DE', '1&1 Drillisch AG'], ['LVGO', 'Livongo Health, Inc.'], ['AAC_delisted', 'AAC Holdings, Inc.'], ['MF', 'MF Global Holdings Ltd.'], ['CRAY', 'CRAY INC'], ['TBIO', 'Translate Bio, Inc.'], ['LKSD', 'LSC Communications, Inc.'], ['PARE', 'PALADIN REALTY INCOME PROPERTIES INC'], ['FCAUS', 'FCA US LLC'], ['C31.SI', 'CapitaLand Limited'], ['MGLN', 'MAGELLAN HEALTH INC'], ['CYIG', 'SPRING PHARMACEUTICAL GROUP, INC.'], ['FFKY', 'FIRST FINANCIAL SERVICE CORP'], ['WORK', 'Slack Technologies, Inc.'], ['EXAM', 'ExamWorks Group, Inc.'], ['CXP', 'COLUMBIA PROPERTY TRUST, INC.'], ['CPLG', 'CorePoint Lodging Inc.'], ['LPT', 'LIBERTY PROPERTY TRUST'], ['RIGHT', 'Right of Reply Ltd'], ['EMIS', 'EMISPHERE TECHNOLOGIES INC'], ['PETM', 'PETSMART INC'], ['GWPH', 'GW PHARMACEUTICALS PLC'], ['LSYN', 'Liberated Syndication Inc.'], ['CHAP', 'Chaparral Energy, Inc.'], ['AM', 'Antero Midstream Partners LP'], ['FBM', 'Foundation Building Materials, Inc.'], ['OTEL', 'OTELCO INC.'], ['MCG', 'MultiChoice (MCG.JOH)'], ['NAVG', 'NAVIGATORS GROUP INC'], ['AXF', 'AXA FINANCIAL INC'], ['ABG.JO', 'Absa Group Ltd (ABG.JOH)'], ['ARI.JO', 'African Rainbow Minerals Ltd (ARI.JOH)'], ['TBS', 'Tiger Brands Ltd (TBS.JOH)'], ['INSV', 'INSITE VISION INC'], ['JGPK', 'JAGGED PEAK, INC.'], ['JAG', 'Jagged Peak Energy Inc.'], ['ONDK', 'On Deck Capital, Inc.'], ['NKT.CO', 'NKT A/S'], ['WPG', 'WASHINGTON PRIME GROUP INC.'], ['RST', 'ROSETTA STONE INC'], ['CYRP', 'CYBRA CORP'], ['SOLY', 'Soliton, Inc.'], ['BCSI', 'BLUE COAT SYSTEMS INC'], ['RLH', 'Red Lion Hotels CORP'], ['FOL', 'FactorShares 2X: Oil Bull/S&P500 Bear'], ['FSU', 'FactorShares 2X: S&P500 Bull/USD Bear'], ['AGHI', 'Agora Holdings, Inc.'], ['BCLR', 'BARCLAY ROAD, INC.'], ['TWER', 'TOWERSTREAM CORP'], ['TCO', 'TAUBMAN CENTERS INC'], ['KLEG', 'KL Energy Corp'], ['CSWG', 'SEN YU INTERNATIONAL HOLDINGS, INC.'], ['HUSI', 'HSBC USA INC /MD/'], ['IPAS', 'IPASS INC'], ['NGRP', 'CRESTWOOD HOLDINGS LP'], ['ENBL', 'Ena

In [6]:
columns = ['ticker', 'name']
columns

['ticker', 'name']

In [7]:
company_list = pd.DataFrame(columns=columns)
company_list

Empty DataFrame
Columns: [ticker, name]
Index: []

In [ ]:
# This block of code creates a list of all companies with tickers.
for ticker in tickers:
    company_list.loc[len(company_list)] = ticker

In [9]:
company_list

          ticker                                         name
0            STL                             STERLING BANCORP
1            NSU                         NEVSUN RESOURCES LTD
2     PINX:ICNAF                        Icanic Brands Co Inc.
3           INFY                                  Infosys Ltd
4           XLRN                         ACCELERON PHARMA INC
...          ...                                          ...
6595        VIOT                    Viomi Technology Co., Ltd
6596       OTGAU                 OTG Acquisition Corp. I Unit
6597         NCT   Intercont (Cayman) Limited Ordinary shares
6598        SSEA  Starry Sea Acquisition Corp Ordinary Shares
6599        LBRX          LB Pharmaceuticals Inc Common Stock

[6600 rows x 2 columns]

In [10]:
company_list[company_list['ticker'] =='AAPL']

     ticker       name
1714   AAPL  APPLE INC

In [11]:
company_list[company_list['ticker'] =='KO']

     ticker          name
1231     KO  COCA COLA CO

In [12]:
top_50_companies =[
{"name" : "Nvidia","ticker": "NVDA"},
{"name" : "Apple Inc.","ticker": "AAPL"},
{"name" : "Microsoft",	"ticker": "MSFT"},
{"name" : "Amazon",	"ticker": "AMZN"},
{"name" : "Meta Platforms",	"ticker": "META"},	
{"name" : "Alphabet Inc. (Class C)","ticker":  "GOOG"},	
{"name" : "Tesla, Inc.", "ticker": "TSLA"},
{"name" : "Walmart", "ticker": "WMT"},
{"name" : "JPMorgan Chase",	"ticker": "JPM"},	
{"name" : "Oracle Corporation",	"ticker": "ORCL"},	
{"name" : "Visa Inc.", "ticker": "V"},
{"name" : "Mastercard",	"ticker": "MA"},
{"name" : "Netflix", "ticker": "NFLX"},	
{"name" : "ExxonMobil",	"ticker": "XOM"},	
{"name" : "Johnson & Johnson", "ticker": "JNJ"},	
{"name" : "Palantir Technologies", "ticker": "PLTR"},	
{"name" : "Costco",	"ticker": "COST"},	
{"name" : "Home Depot",	"ticker": "HD"},	
{"name" : "Bank of America", "ticker": "BAC"},	
{"name" : "Procter & Gamble", "ticker": "PG"},	
{"name" : "Chevron Corporation", "ticker": "CVX"},	
{"name" : "Coca-Cola Company", "ticker": "KO"},	
{"name" : "Cisco", "ticker": "CSCO"},	
{"name" : "Wells Fargo","ticker": "WFC"},
{"name" : "IBM", "ticker": "IBM"},	
{"name" : "T-Mobile US", "ticker": "TMUS"},	
{"name" : "Morgan Stanley",	"ticker": "MS"},	
{"name" : "Salesforce",	"ticker": "CRM"},	
{"name" : "Caterpillar Inc.","ticker": "CAT"},
{"name" : "American Express", "ticker": "AXP"},
{"name" : "Philip Morris International","ticker":  "PM"},	
{"name" : "Goldman Sachs", "ticker": "GS"},	
{"name" : "RTX Corporation", "ticker": "RTX"},	
{"name" : "Abbott Laboratories", "ticker": "ABT"},
{"name" : "McDonald's",	"ticker": "MCD"},	
{"name" : "PepsiCo", "ticker": "PEP"},
{"name" : "Walt Disney Company","ticker":  "DIS"},	
{"name" : "ServiceNow",	"ticker": "NOW"},
{"name" : "AT&T", "ticker": "T"},
{"name" : "Intel", "ticker": "INTC"},
]

In [13]:
len(top_50_companies)

40

In [14]:
top_50_tickers=[]
for company in top_50_companies:
    top_50_tickers.append(company['ticker'])

top_50_tickers = pd.Series(top_50_tickers)
top_50_tickers

0     NVDA
1     AAPL
2     MSFT
3     AMZN
4     META
5     GOOG
6     TSLA
7      WMT
8      JPM
9     ORCL
10       V
11      MA
12    NFLX
13     XOM
14     JNJ
15    PLTR
16    COST
17      HD
18     BAC
19      PG
20     CVX
21      KO
22    CSCO
23     WFC
24     IBM
25    TMUS
26      MS
27     CRM
28     CAT
29     AXP
30      PM
31      GS
32     RTX
33     ABT
34     MCD
35     PEP
36     DIS
37     NOW
38       T
39    INTC
dtype: object

In [15]:
print((top_50_tickers.isin(company_list['ticker'])).sum(), len(top_50_tickers))
## if they are the same the list is good to go!
# This is a data validation step

40 40

### Getting Share price data

In [21]:
endpoint_url= f"{base_url}/prices/compact"

params = {'ticker': 'AAPL, NVDA'}

price_data_response = requests.get(endpoint_url, headers=headers, params=params)

if price_data_response.status_code == 200:
    # Parse the JSON response
    price_data = price_data_response.json()
else:
    print(f"Failed to retrieve data. Status code: {price_data_response.status_code}")

In [22]:
price_data[0] #STL --> works

{'columns': ['Date',
  'Dividend Paid',
  'Common Shares Outstanding',
  'Last Closing Price',
  'Adjusted Closing Price',
  'Highest Price',
  'Lowest Price',
  'Opening Price',
  'Trading Volume'],
 'name': 'NVIDIA CORP',
 'id': 172199,
 'ticker': 'NVDA',
 'currency': 'USD',
 'isin': 'US67066G1040',
 'data': [['2018-11-08',
   None,
   24440000000,
   5.15,
   5.1,
   5.29,
   5.1,
   5.29,
   511352920],
  ['2018-11-09', None, 24400000000, 5.14, 5.09, 5.23, 5.03, 5.06, 413241960],
  ['2018-11-12', None, 24400000000, 4.74, 4.69, 5.07, 4.72, 5.05, 617117880],
  ['2018-11-13', None, 24400000000, 4.98, 4.94, 5.11, 4.83, 4.84, 644711000],
  ['2018-11-14', None, 24400000000, 4.93, 4.88, 5.17, 4.82, 5.16, 526578840],
  ['2018-11-15', None, 24400000000, 5.06, 5.01, 5.13, 4.89, 4.92, 840708640],
  ['2018-11-16', None, 24400000000, 4.11, 4.07, 4.27, 4.04, 4.08, 1963519080],
  ['2018-11-19', None, 24400000000, 3.62, 3.58, 4.05, 3.62, 4.04, 1697820200],
  ['2018-11-20', None, 24400000000, 3.73, 3.69, 3.86, 3.33, 3.35, 1692033120],
  ['2018-11-21', None, 24400000000, 3.62, 3.58, 3.88, 3.59, 3.87, 1025494000],
  ['2018-11-23', None, 24400000000, 3.62, 3.59, 3.74, 3.57, 3.58, 411968440],
  ['2018-11-26', None, 24400000000, 3.83, 3.79, 3.84, 3.66, 3.75, 814832240],
  ['2018-11-27', None, 24400000000, 3.84, 3.81, 3.93, 3.76, 3.8, 738060240],
  ['2018-11-28', None, 24400000000, 4.0, 3.96, 4.01, 3.83, 3.96, 804525480],
  ['2018-11-29', 0.0, 24400000000, 3.93, 3.9, 4.04, 3.9, 4.0, 549173600],
  ['2018-11-30', None, 24400000000, 4.09, 4.05, 4.1, 3.89, 3.94, 729564560],
  ['2018-12-03', None, 24400000000, 4.25, 4.22, 4.37, 4.18, 4.32, 890804360],
  ['2018-12-04', None, 24400000000, 3.93, 3.9, 4.21, 3.91, 4.21, 812111480],
  ['2018-12-06', None, 24400000000, 3.96, 3.92, 3.96, 3.77, 3.79, 692309640],
  ['2018-12-07', None, 24400000000, 3.69, 3.66, 3.97, 3.64, 3.96, 681677960],
  ['2018-12-10', None, 24400000000, 3.8, 3.77, 3.82, 3.64, 3.65, 629473400],
  ['2018-12-11', None, 24400000000, 3.7, 3.67, 3.9, 3.62, 3.89, 671913280],
  ['2018-12-12', None, 24400000000, 3.72, 3.69, 3.82, 3.62, 3.71, 654135920],
  ['2018-12-13', None, 24400000000, 3.72, 3.69, 3.83, 3.69, 3.77, 471384960],
  ['2018-12-14', None, 24400000000, 3.66, 3.63, 3.76, 3.64, 3.68, 471821240],
  ['2018-12-17', None, 24400000000, 3.59, 3.56, 3.7, 3.53, 3.63, 662867320],
  ['2018-12-18', None, 24400000000, 3.67, 3.64, 3.76, 3.61, 3.63, 564370040],
  ['2018-12-19', None, 24400000000, 3.46, 3.43, 3.69, 3.41, 3.64, 745365880],
  ['2018-12-20', None, 24400000000, 3.38, 3.35, 3.54, 3.32, 3.45, 749587880],
  ['2018-12-21', None, 24400000000, 3.24, 3.21, 3.44, 3.21, 3.4, 863741000],
  ['2018-12-24', None, 24400000000, 3.18, 3.15, 3.25, 3.11, 3.16, 463839120],
  ['2018-12-26', None, 24400000000, 3.33, 3.3, 3.33, 3.11, 3.22, 695099360],
  ['2018-12-27', None, 24400000000, 3.28, 3.25, 3.31, 3.13, 3.27, 637043200],
  ['2018-12-28', None, 24400000000, 3.34, 3.31, 3.43, 3.26, 3.3, 628492760],
  ['2018-12-31', None, 24400000000, 3.34, 3.31, 3.42, 3.31, 3.38, 465140120],
  ['2019-01-02', None, 24400000000, 3.41, 3.38, 3.46, 3.25, 3.27, 508753600],
  ['2019-01-03', None, 24400000000, 3.2, 3.17, 3.38, 3.19, 3.34, 705551440],
  ['2019-01-04', None, 24400000000, 3.4, 3.38, 3.44, 3.24, 3.27, 585619320],
  ['2019-01-07', None, 24400000000, 3.58, 3.56, 3.62, 3.41, 3.46, 709159200],
  ['2019-01-08', None, 24400000000, 3.5, 3.47, 3.67, 3.42, 3.67, 786017160],
  ['2019-01-09', None, 24400000000, 3.56, 3.54, 3.61, 3.5, 3.55, 617259000],
  ['2019-01-10', None, 24400000000, 3.63, 3.6, 3.64, 3.48, 3.54, 523156240],
  ['2019-01-11', None, 24400000000, 3.72, 3.69, 3.74, 3.58, 3.61, 874762640],
  ['2019-01-14', None, 24400000000, 3.76, 3.73, 3.79, 3.64, 3.67, 730169960],
  ['2019-01-15', None, 24400000000, 3.75, 3.72, 3.83, 3.73, 3.79, 617010040],
  ['2019-01-16', None, 24400000000, 3.72, 3.69, 3.81, 3.72, 3.77, 470103680],
  ['2019-01-17', None, 24400000000, 3.79, 3.76, 3.83, 3.66, 3.69, 493436200],
  ['2019-01-18', None, 24400000000, 3.92, 3.89, 3.95, 3.79, 3.84, 651336920],
  ['2019-01-22', None, 24400000000, 3.72, 3.69, 3.9, 3.69, 3.89, 661551040],
  ['2019-01-23', None, 24400000000, 3.73, 3.7, 3.86, 3.7, 3.77, 591021800],
  ['2019-01-24', None, 24400000000, 3.95, 3.91, 3.96, 3.81, 3.82, 708970440],
  ['2019-01-25', None, 24400000000, 4.0, 3.97, 4.02, 3.78, 3.89, 1155221880],
  ['2019-01-28', None, 24240000000, 3.45, 3.42, 3.54, 3.27, 3.41, 2511526760],
  ['2019-01-29', None, 24240000000, 3.29, 3.26, 3.45, 3.28, 3.4, 1153933880],
  ['2019-01-30', None, 24240000000, 3.43, 3.41, 3.45, 3.29, 3.37, 974229560],
  ['2019-01-31', None, 24240000000, 3.59, 3.56, 3.63, 3.41, 3.43, 842853520],
  ['2019-02-01', None, 24240000000, 3.62, 3.59, 3.67, 3.56, 3.61, 625047000],
  ['2019-02-04', None, 24240000000, 3.73, 3.7, 3.77, 3.61, 3.63, 528600720],
  ['2019-02-05', None, 24240000000, 3.75, 3.72, 3.79, 3.71, 3.74, 542425000],
  ['2019-02-06', None, 24240000000, 3.83, 3.79, 3.89, 3.78, 3.78, 702465880],
  ['2019-02-07', None, 24240000000, 3.69, 3.66, 3.78, 3.64, 3.78, 637120000],
  ['2019-02-08', None, 24240000000, 3.7, 3.67, 3.71, 3.6, 3.62, 461605480],
  ['2019-02-11', None, 24240000000, 3.66, 3.63, 3.71, 3.61, 3.66, 495180600],
  ['2019-02-12', None, 24240000000, 3.78, 3.75, 3.79, 3.69, 3.7, 591060520],
  ['2019-02-13', None, 24240000000, 3.82, 3.79, 3.9, 3.8, 3.81, 605372080],
  ['2019-02-14', None, 24240000000, 3.86, 3.83, 3.89, 3.78, 3.82, 827262960],
  ['2019-02-15', None, 24240000000, 3.93, 3.9, 4.1, 3.91, 4.07, 1516749360],
  ['2019-02-19', None, 24240000000, 3.92, 3.88, 4.0, 3.9, 3.92, 551892640],
  ['2019-02-20', None, 24240000000, 3.96, 3.93, 4.03, 3.93, 3.95, 540989480],
  ['2019-02-21', None, 24240000000, 3.89, 3.86, 4.0, 3.88, 3.98, 448546720],
  ['2019-02-22', None, 24240000000, 3.98, 3.95, 4.0, 3.93, 3.95, 401741240],
  ['2019-02-25', None, 24240000000, 3.97, 3.93, 4.13, 3.96, 4.06, 656019240],
  ['2019-02-26', None, 24240000000, 3.93, 3.9, 4.02, 3.89, 3.96, 488462840],
  ['2019-02-27', None, 24240000000, 3.89, 3.85, 3.94, 3.83, 3.91, 500255240],
  ['2019-02-28', 0.0, 24240000000, 3.86, 3.83, 3.9, 3.83, 3.88, 324942600],
  ['2019-03-01', None, 24240000000, 3.91, 3.88, 3.95, 3.85, 3.91, 357187120],
  ['2019-03-04', None, 24240000000, 3.92, 3.89, 3.97, 3.86, 3.95, 409990000],
  ['2019-03-05', None, 24240000000, 3.91, 3.88, 3.95, 3.85, 3.9, 362924760],
  ['2019-03-06', None, 24240000000, 3.8, 3.77, 3.91, 3.8, 3.9, 403525960],
  ['2019-03-07', None, 24240000000, 3.73, 3.7, 3.79, 3.69, 3.78, 450105320],
  ['2019-03-08', None, 24240000000, 3.77, 3.74, 3.78, 3.62, 3.64, 422414840],
  ['2019-03-11', None, 24240000000, 4.03, 4.0, 4.05, 3.74, 3.79, 859726000],
  ['2019-03-12', None, 24240000000, 4.06, 4.03, 4.11, 3.98, 4.06, 579574720],
  ['2019-03-13', None, 24240000000, 4.22, 4.19, 4.25, 4.09, 4.1, 768900720],
  ['2019-03-14', None, 24240000000, 4.14, 4.11, 4.24, 4.13, 4.22, 519385200],
  ['2019-03-15', None, 24240000000, 4.25, 4.21, 4.29, 4.18, 4.18, 661459280],
  ['2019-03-18', None, 24240000000, 4.22, 4.19, 4.33, 4.2, 4.28, 486993160],
  ['2019-03-19', None, 24240000000, 4.39, 4.36, 4.44, 4.3, 4.32, 854972400],
  ['2019-03-20', None, 24240000000, 4.36, 4.33, 4.48, 4.33, 4.42, 719148600],
  ['2019-03-21', None, 24240000000, 4.6, 4.57, 4.62, 4.38, 4.38, 824310680],
  ['2019-03-22', None, 24240000000, 4.44, 4.41, 4.62, 4.42, 4.57, 747643480],
  ['2019-03-25', None, 24240000000, 4.34, 4.31, 4.46, 4.28, 4.4, 525212040],
  ['2019-03-26', None, 24240000000, 4.42, 4.39, 4.54, 4.37, 4.49, 703507120],
  ['2019-03-27', None, 24240000000, 4.41, 4.38, 4.49, 4.34, 4.45, 474371760],
  ['2019-03-28', None, 24240000000, 4.43, 4.4, 4.5, 4.38, 4.44, 480264080],
  ['2019-03-29', None, 24240000000, 4.49, 4.46, 4.51, 4.45, 4.5, 456895160],
  ['2019-04-01', None, 24240000000, 4.56, 4.52, 4.59, 4.51, 4.58, 483824480],
  ['2019-04-02', None, 24240000000, 4.58, 4.54, 4.62, 4.54, 4.58, 440919840],
  ['2019-04-03', None, 24240000000, 4.72, 4.68, 4.78, 4.62, 4.62, 788778720],
  ['2019-04-04', None, 24240000000, 4.71, 4.67, 4.75, 4.64, 4.7, 457376760],
  ['2019-04-05', None, 24240000000, 4.77, 4.74, 4.79, 4.71, 4.75, 481745960],
  ['2019-04-08', None, 24240000000, 4.79, 4.76, 4.82, 4.72, 4.74, 424193920],
  ['2019-04-09', None, 24240000000, 4.73, 4.7, 4.77, 4.69, 4.76, 439972800],
  ['2019-04-10', None, 24240000000, 4.8, 4.77, 4.83, 4.73, 4.73, 444772280],
  ['2019-04-11', None, 24240000000, 4.79, 4.75, 4.84, 4.74, 4.8, 374601480],
  ['2019-04-12', None, 24240000000, 4.75, 4.72, 4.83, 4.74, 4.83, 471706560],
  ['2019-04-15', None, 24240000000, 4.62, 4.58, 4.75, 4.58, 4.74, 440093800],
  ['2019-04-16', None, 24240000000, 4.71, 4.67, 4.72, 4.62, 4.66, 394963640],
  ['2019-04-17', None, 24240000000, 4.68, 4.65, 4.76, 4.66, 4.74, 351002720],
  ['2019-04-18', None, 24240000000, 4.66, 4.62, 4.72, 4.63, 4.69, 380988160],
  ['2019-04-22', None, 24240000000, 4.71, 4.68, 4.73, 4.6, 4.63, 279935520],
  ['2019-04-23', None, 24240000000, 4.77, 4.73, 4.8, 4.72, 4.72, 346855240],
  ['2019-04-24', None, 24240000000, 4.78, 4.74, 4.82, 4.72, 4.78, 318204800],
  ['2019-04-25', None, 24240000000, 4.67, 4.64, 4.76, 4.59, 4.74, 499297480],
  ['2019-04-26', None, 24240000000, 4.45, 4.42, 4.52, 4.33, 4.52, 868989160],
  ['2019-04-29', None, 24360000000, 4.48, 4.45, 4.51, 4.39, 4.46, 391919320],
  ['2019-04-30', None, 24360000000, 4.53, 4.49, 4.55, 4.43, 4.45, 362921600],
  ['2019-05-01', None, 24360000000, 4.51, 4.48, 4.62, 4.51, 4.58, 354281240],
  ['2019-05-02', None, 24360000000, 4.58, 4.55, 4.62, 4.48, 4.52, 394685400],
  ['2019-05-03', None, 24360000000, 4.58, 4.54, 4.6, 4.51, 4.59, 336823480],
  ['2019-05-06', None, 24360000000, 4.5, 4.46, 4.51, 4.35, 4.39, 422177800],
  ['2019-05-07', None, 24360000000, 4.33, 4.3, 4.45, 4.28, 4.45, 555218320],
  ['2019-05-08', None, 24360000000, 4.35, 4.32, 4.43, 4.29, 4.3, 419166160],
  ['2019-05-09', None, 24360000000, 4.25, 4.22, 4.29, 4.13, 4.28, 660246560],
  ['2019-05-10', None, 24360000000, 4.22, 4.19, 4.29, 4.1, 4.22, 569498040],
  ['2019-05-13', None, 24360000000, 3.96, 3.93, 4.11, 3.95, 4.09, 656912760],
  ['2019-05-14', None, 24360000000, 4.05, 4.02, 4.09, 3.96, 4.0, 524878880],
  ['2019-05-15', None, 24360000000, 3.99, 3.96, 4.03, 3.94, 4.0, 502320040],
  ['2019-05-16', None, 24360000000, 4.0, 3.98, 4.05, 3.94, 3.98, 781088160],
  ['2019-05-17', None, 24360000000, 3.91, 3.88, 4.09, 3.87, 3.96, 1022067920],
  ['2019-05-20', None, 24360000000, 3.79, 3.77, 3.87, 3.77, 3.81, 572065360],
  ['2019-05-21', None, 24360000000, 3.88, 3.85, 3.89, 3.82, 3.85, 361849880],
  ['2019-05-22', None, 24360000000, 3.81, 3.78, 3.86, 3.79, 3.84, 325869600],
  ['2019-05-23', None, 24360000000, 3.68, 3.66, 3.74, 3.62, 3.74, 591844360],
  ['2019-05-24', None, 24360000000, 3.63, 3.6, 3.74, 3.62, 3.7, 357585280],
  ['2019-05-28', None, 24360000000, 3.58, 3.56, 3.68, 3.58, 3.65, 428354080],
  ['2019-05-29', None, 24360000000, 3.51, 3.48, 3.57, 3.47, 3.54, 559801480],
  ['2019-05-30', 0.0, 24360000000, 3.48, 3.46, 3.54, 3.44, 3.51, 394299600],
  ['2019-05-31', None, 24360000000, 3.39, 3.37, 3.5, 3.38, 3.43, 389719680],
  ['2019-06-03', None, 24360000000, 3.34, 3.32, 3.44, 3.31, 3.4, 478643200],
  ['2019-06-04', None, 24360000000, 3.58, 3.55, 3.58, 3.39, 3.41, 641835400],
  ['2019-06-05', None, 24360000000, 3.53, 3.51, 3.65, 3.5, 3.65, 511615400],
  ['2019-06-06', None, 24360000000, 3.59, 3.57, 3.62, 3.53, 3.54, 408138480],
  ['2019-06-07', None, 24360000000, 3.64, 3.62, 3.67, 3.58, 3.6, 348857520],
  ['2019-06-10', None, 24360000000, 3.71, 3.69, 3.78, 3.69, 3.69, 402780880],
  ['2019-06-11', None, 24360000000, 3.77, 3.75, 3.81, 3.73, 3.77, 383870040],
  ['2019-06-12', None, 24360000000, 3.65, 3.63, 3.73, 3.64, 3.73, 358891920],
  ['2019-06-13', None, 24360000000, 3.71, 3.68, 3.73, 3.66, 3.68, 308081080],
  ['2019-06-14', None, 24360000000, 3.62, 3.59, 3.64, 3.57, 3.61, 394426240],
  ['2019-06-17', None, 24360000000, 3.63, 3.6, 3.66, 3.59, 3.61, 276041480],
  ['2019-06-18', None, 24360000000, 3.82, 3.8, 3.88, 3.68, 3.69, 581918000],
  ['2019-06-19', None, 24360000000, 3.83, 3.8, 3.87, 3.8, 3.86, 331643960],
  ['2019-06-20', None, 24360000000, 3.85, 3.83, 3.93, 3.84, 3.92, 350167280],
  ['2019-06-21', None, 24360000000, 3.79, 3.77, 3.89, 3.79, 3.84, 434426880],
  ['2019-06-24', None, 24360000000, 3.82, 3.79, 3.85, 3.77, 3.82, 282948720],
  ['2019-06-25', None, 24360000000, 3.79, 3.76, 3.9, 3.78, 3.82, 311866440],
  ['2019-06-26', None, 24360000000, 3.98, 3.96, 4.04, 3.9, 3.92, 584073000],
  ['2019-06-27', None, 24360000000, 4.08, 4.06, 4.1, 4.03, 4.07, 445441520],
  ['2019-06-28', None, 24360000000, 4.11, 4.08, 4.13, 4.06, 4.12, 397666360],
  ['2019-07-01', None, 24360000000, 4.15, 4.13, 4.35, 4.12, 4.31, 711533080],
  ['2019-07-02', None, 24360000000, 4.06, 4.03, 4.16, 4.04, 4.14, 400227520],
  ['2019-07-03', None, 24360000000, 4.07, 4.04, 4.08, 4.01, 4.08, 246634240],
  ['2019-07-05', None, 24360000000, 4.01, 3.98, 4.01, 3.94, 4.01, 396553880],
  ['2019-07-08', None, 24360000000, 3.93, 3.91, 3.96, 3.9, 3.95, 329786760],
  ['2019-07-09', None, 24360000000, 3.93, 3.91, 3.96, 3.88, 3.89, 342860480],
  ['2019-07-10', None, 24360000000, 4.0, 3.98, 4.06, 3.96, 3.98, 452075960],
  ['2019-07-11', None, 24360000000, 4.16, 4.13, 4.2, 4.04, 4.08, 682558560],
  ['2019-07-12', None, 24360000000, 4.19, 4.16, 4.26, 4.18, 4.18, 506392640],
  ['2019-07-15', None, 24360000000, 4.18, 4.16, 4.23, 4.15, 4.21, 289839720],
  ['2019-07-16', None, 24360000000, 4.18, 4.15, 4.2, 4.12, 4.17, 341443920],
  ['2019-07-17', None, 24360000000, 4.24, 4.22, 4.25, 4.15, 4.18, 348204280],
  ['2019-07-18', None, 24360000000, 4.25, 4.23, 4.32, 4.2, 4.25, 443178960],
  ['2019-07-19', None, 24360000000, 4.21, 4.19, 4.3, 4.21, 4.29, 344895800],
  ['2019-07-22', None, 24360000000, 4.28, 4.26, 4.3, 4.22, 4.23, 315939920],
  ['2019-07-23', None, 24360000000, 4.39, 4.36, 4.39, 4.31, 4.32, 428176560],
  ['2019-07-24', None, 24360000000, 4.47, 4.44, 4.47, 4.36, 4.43, 366237480],
  ['2019-07-25', None, 24360000000, 4.33, 4.31, 4.44, 4.31, 4.42, 392698120],
  ['2019-07-26', None, 24360000000, 4.38, 4.35, 4.42, 4.36, 4.36, 274159880],
  ['2019-07-29', None, 24360000000, 4.37, 4.34, 4.39, 4.28, 4.37, 248161960],
  ['2019-07-30', None, 24360000000, 4.39, 4.36, 4.4, 4.31, 4.32, 197770440],
  ['2019-07-31', None, 24360000000, 4.22, 4.19, 4.36, 4.18, 4.35, 359415640],
  ['2019-08-01', None, 24360000000, 4.12, 4.1, 4.32, 4.07, 4.23, 421212560],
  ['2019-08-02', None, 24360000000, 4.03, 4.01, 4.1, 3.98, 4.03, 428349280],
  ['2019-08-05', None, 24360000000, 3.77, 3.75, 3.85, 3.72, 3.85, 589157440],
  ['2019-08-06', None, 24360000000, 3.81, 3.79, 3.89, 3.76, 3.85, 361270680],
  ['2019-08-07', None, 24360000000, 3.85, 3.82, 3.86, 3.73, 3.75, 372561800],
  ['2019-08-08', None, 24360000000, 3.96, 3.93, 3.96, 3.85, 3.91, 309298880],
  ['2019-08-09', None, 24360000000, 3.85, 3.83, 3.92, 3.8, 3.92, 341816720],
  ['2019-08-12', None, 24360000000, 3.79, 3.76, 3.85, 3.76, 3.8, 279200480],
  ['2019-08-13', None, 24360000000, 3.9, 3.88, 3.95, 3.75, 3.78, 360512440],
  ['2019-08-14', None, 24360000000, 3.75, 3.73, 3.82, 3.71, 3.81, 419881320],
  ['2019-08-15', None, 24360000000, 3.72, 3.7, 3.79, 3.68, 3.77, 554462040],
  ['2019-08-16', None, 24360000000, 3.99, 3.96, 4.04, 3.92, 3.98, 1015385120],
  ['2019-08-19', None, 24360000000, 4.27, 4.24, 4.29, 4.09, 4.1, 816322440],
  ['2019-08-20', None, 24360000000, 4.2, 4.17, 4.26, 4.18, 4.26, 463521600],
  ['2019-08-21', None, 24360000000, 4.28, 4.25, 4.34, 4.24, 4.26, 427910920],
  ['2019-08-22', None, 24360000000, 4.29, 4.26, 4.33, 4.25, 4.29, 303756720],
  ['2019-08-23', None, 24360000000, 4.06, 4.04, 4.26, 4.04, 4.21, 569497320],
  ['2019-08-26', None, 24360000000, 4.14, 4.11, 4.16, 4.1, 4.14, 318594160],
  ['2019-08-27', None, 24360000000, 4.04, 4.02, 4.18, 4.02, 4.17, 291549560],
  ['2019-08-28', 0.0, 24360000000, 4.03, 4.01, 4.08, 3.98, 4.01, 255068760],
  ['2019-08-29', None, 24360000000, 4.17, 4.15, 4.21, 4.12, 4.12, 358373040],
  ['2019-08-30', None, 24360000000, 4.19, 4.17, 4.27, 4.17, 4.22, 290908480],
  ['2019-09-03', None, 24360000000, 4.1, 4.08, 4.15, 4.08, 4.11, 296510800],
  ['2019-09-04', None, 24360000000, 4.22, 4.2, 4.23, 4.17, 4.17, 228120360],
  ['2019-09-05', None, 24360000000, 4.49, 4.47, 4.5, 4.32, 4.32, 696485000],
  ['2019-09-06', None, 24360000000, 4.47, 4.44, 4.53, 4.43, 4.47, 376976760],
  ['2019-09-09', None, 24360000000, 4.51, 4.49, 4.6, 4.5, 4.5, 417525320],
  ['2019-09-10', None, 24360000000, 4.58, 4.56, 4.61, 4.47, 4.48, 352812200],
  ['2019-09-11', None, 24360000000, 4.61, 4.58, 4.66, 4.57, 4.59, 361511280],
  ['2019-09-12', None, 24360000000, 4.61, 4.58, 4.71, 4.6, 4.66, 327841000],
  ['2019-09-13', None, 24360000000, 4.55, 4.53, 4.58, 4.5, 4.54, 324591480],
  ['2019-09-16', None, 24360000000, 4.51, 4.48, 4.54, 4.46, 4.47, 231831840],
  ['2019-09-17', None, 24360000000, 4.53, 4.5, 4.53, 4.47, 4.51, 228473120],
  ['2019-09-18', None, 24360000000, 4.5, 4.48, 4.54, 4.41, 4.52, 264037680],
  ['2019-09-19', None, 24360000000, 4.42, 4.4, 4.52, 4.41, 4.51, 256342760],
  ['2019-09-20', None, 24360000000, 4.32, 4.3, 4.45, 4.31, 4.42, 357251800],
  ['2019-09-23', None, 24360000000, 4.37, 4.35, 4.42, 4.31, 4.32, 255825880],
  ['2019-09-24', None, 24360000000, 4.31, 4.29, 4.43, 4.28, 4.4, 321241800],
  ['2019-09-25', None, 24360000000, 4.46, 4.43, 4.48, 4.27, 4.31, 313106880],
  ['2019-09-26', None, 24360000000, 4.43, 4.41, 4.45, 4.38, 4.45, 237825920],
  ['2019-09-27', None, 24360000000, 4.29, 4.27, 4.44, 4.23, 4.39, 365958960],
  ['2019-09-30', None, 24360000000, 4.35, 4.33, 4.36, 4.29, 4.32, 193199080],
  ['2019-10-01', None, 24360000000, 4.35, 4.33, 4.53, 4.35, 4.38, 367566000],
  ['2019-10-02', None, 24360000000, 4.33, 4.3, 4.34, 4.25, 4.33, 295661760],
  ['2019-10-03', None, 24360000000, 4.53, 4.51, 4.54, 4.3, 4.33, 462730600],
  ['2019-10-04', None, 24360000000, 4.55, 4.53, 4.58, 4.47, 4.54, 267960200],
  ['2019-10-07', None, 24360000000, 4.61, 4.58, 4.71, 4.61, 4.61, 488313560],
  ['2019-10-08', None, 24360000000, 4.43, 4.41, 4.52, 4.41, 4.52, 449342640],
  ['2019-10-09', None, 24360000000, 4.52, 4.49, 4.57, 4.48, 4.51, 307883280],
  ['2019-10-10', None, 24360000000, 4.58, 4.55, 4.63, 4.51, 4.52, 327515560],
  ['2019-10-11', None, 24360000000, 4.65, 4.63, 4.73, 4.64, 4.66, 450866720],
  ['2019-10-14', None, 24360000000, 4.66, 4.64, 4.68, 4.61, 4.64, 210335760],
  ['2019-10-15', None, 24360000000, 4.91, 4.88, 4.98, 4.74, 4.75, 667985320],
  ['2019-10-16', None, 24360000000, 4.86, 4.83, 4.98, 4.84, 4.88, 432753120],
  ['2019-10-17', None, 24360000000, 4.86, 4.83, 4.95, 4.8, 4.9, 264316960],
  ['2019-10-18', None, 24360000000, 4.76, 4.74, 4.89, 4.69, 4.86, 301921560],
  ['2019-10-21', None, 24360000000, 4.9, 4.88, 4.91, 4.8, 4.82, 261868440],
  ['2019-10-22', None, 24360000000, 4.89, 4.87, 5.06, 4.88, 4.96, 337369120],
  ['2019-10-23', None, 24360000000, 4.88, 4.85, 4.89, 4.78, 4.81, 285770000],
  ['2019-10-24', None, 24360000000, 4.92, 4.9, 4.96, 4.88, 4.92, 239037320],
  ['2019-10-25', None, 24360000000, 5.11, 5.09, 5.13, 4.99, 5.0, 423091520],
  ['2019-10-28', None, 24480000000, 5.17, 5.14, 5.22, 5.13, 5.16, 324668720],
  ['2019-10-29', None, 24480000000, 5.07, 5.05, 5.16, 5.05, 5.16, 211236800],
  ['2019-10-30', None, 24480000000, 5.08, 5.05, 5.11, 5.01, 5.1, 205961520],
  ['2019-10-31', None, 24480000000, 5.03, 5.0, 5.08, 4.95, 5.05, 209732600],
  ['2019-11-01', None, 24480000000, 5.06, 5.04, 5.1, 4.96, 4.99, 283638240],
  ['2019-11-04', None, 24480000000, 5.26, 5.24, 5.28, 5.12, 5.15, 376716200],
  ['2019-11-05', None, 24480000000, 5.24, 5.21, 5.29, 5.19, 5.26, 300868480],
  ['2019-11-06', None, 24480000000, 5.19, 5.16, 5.24, 5.1, 5.22, 269013400],
  ['2019-11-07', None, 24480000000, 5.21, 5.18, 5.29, 5.16, 5.28, 280339920],
  ['2019-11-08', None, 24480000000, 5.19, 5.17, 5.23, 5.15, 5.19, 189407480],
  ['2019-11-11', None, 24480000000, 5.2, 5.18, 5.23, 5.11, 5.19, 243789440],

In [23]:
price_data[1] #AAPL --> works

{'columns': ['Date',
  'Dividend Paid',
  'Common Shares Outstanding',
  'Last Closing Price',
  'Adjusted Closing Price',
  'Highest Price',
  'Lowest Price',
  'Opening Price',
  'Trading Volume'],
 'name': 'APPLE INC',
 'id': 111052,
 'ticker': 'AAPL',
 'currency': 'USD',
 'isin': 'US0378331005',
 'data': [['2018-11-08',
   0.18,
   18981592000,
   52.12,
   49.61,
   52.53,
   51.69,
   52.49,
   101450544],
  ['2018-11-09',
   None,
   18981592000,
   51.12,
   48.65,
   51.5,
   50.56,
   51.39,
   137463000],
  ['2018-11-12',
   None,
   18981592000,
   48.54,
   46.2,
   49.96,
   48.45,
   49.75,
   204542072],
  ['2018-11-13',
   None,
   18981592000,
   48.06,
   45.74,
   49.3,
   47.86,
   47.91,
   187531744],
  ['2018-11-14',
   None,
   18981592000,
   46.7,
   44.45,
   48.62,
   46.48,
   48.48,
   243203828],
  ['2018-11-15',
   None,
   18981592000,
   47.85,
   45.55,
   47.99,
   46.73,
   47.1,
   185915204],
  ['2018-11-16',
   None,
   18981592000,
   48.38,
   46.05,
   48.74,
   47.37,
   47.62,
   147713012],
  ['2018-11-19',
   None,
   18981592000,
   46.47,
   44.23,
   47.67,
   46.25,
   47.5,
   167683488],
  ['2018-11-20',
   None,
   18981592000,
   44.24,
   42.11,
   45.37,
   43.88,
   44.59,
   271300988],
  ['2018-11-21',
   None,
   18981592000,
   44.2,
   42.06,
   45.07,
   44.14,
   44.93,
   124496840],
  ['2018-11-23',
   None,
   18981592000,
   43.07,
   41.0,
   44.15,
   43.02,
   43.73,
   94495888],
  ['2018-11-26',
   None,
   18981592000,
   43.66,
   41.55,
   43.74,
   42.56,
   43.56,
   179994080],
  ['2018-11-27',
   None,
   18981592000,
   43.56,
   41.46,
   43.69,
   42.72,
   42.88,
   165549508],
  ['2018-11-28',
   None,
   18981592000,
   45.23,
   43.05,
   45.32,
   43.73,
   44.18,
   184250156],
  ['2018-11-29',
   None,
   18981592000,
   44.89,
   42.72,
   45.7,
   44.42,
   45.66,
   167079968],
  ['2018-11-30',
   None,
   18981592000,
   44.65,
   42.49,
   45.08,
   44.26,
   45.07,
   158126196],
  ['2018-12-03',
   None,
   18981592000,
   46.2,
   43.98,
   46.23,
   45.3,
   46.12,
   163192008],
  ['2018-12-04',
   None,
   18981592000,
   44.17,
   42.04,
   45.6,
   44.07,
   45.24,
   165377128],
  ['2018-12-06',
   None,
   18981592000,
   43.68,
   41.57,
   43.7,
   42.6,
   42.94,
   172393640],
  ['2018-12-07',
   None,
   18981592000,
   42.12,
   40.09,
   43.62,
   42.08,
   43.37,
   169126524],
  ['2018-12-10',
   None,
   18981592000,
   42.4,
   40.36,
   42.52,
   40.83,
   41.25,
   248103976],
  ['2018-12-11',
   None,
   18981592000,
   42.16,
   40.13,
   42.95,
   41.75,
   42.91,
   189126660],
  ['2018-12-12',
   None,
   18981592000,
   42.27,
   40.24,
   42.98,
   42.26,
   42.6,
   142510696],
  ['2018-12-13',
   None,
   18981592000,
   42.74,
   40.68,
   43.14,
   42.39,
   42.62,
   127591308],
  ['2018-12-14',
   None,
   18981592000,
   41.37,
   39.38,
   42.27,
   41.32,
   42.25,
   162814840],
  ['2018-12-17',
   None,
   18981592000,
   40.98,
   39.01,
   42.09,
   40.68,
   41.36,
   177151688],
  ['2018-12-18',
   None,
   18981592000,
   41.52,
   39.52,
   41.88,
   41.1,
   41.34,
   135366072],
  ['2018-12-19',
   None,
   18981592000,
   40.22,
   38.28,
   41.86,
   39.77,
   41.5,
   196189188],
  ['2018-12-20',
   None,
   18981592000,
   39.21,
   37.32,
   40.53,
   38.83,
   40.1,
   259091840],
  ['2018-12-21',
   None,
   18981592000,
   37.68,
   35.87,
   39.54,
   37.41,
   39.22,
   382977536],
  ['2018-12-24',
   None,
   18981592000,
   36.71,
   34.94,
   37.89,
   36.65,
   37.04,
   148676928],
  ['2018-12-26',
   None,
   18981592000,
   39.29,
   37.4,
   39.31,
   36.68,
   37.08,
   234330176],
  ['2018-12-27',
   None,
   18981592000,
   39.04,
   37.16,
   39.19,
   37.52,
   38.96,
   212468260],
  ['2018-12-28',
   None,
   18981592000,
   39.06,
   37.17,
   39.63,
   38.64,
   39.38,
   169165696],
  ['2018-12-31',
   None,
   18919212000,
   39.44,
   37.53,
   39.84,
   39.12,
   39.63,
   140013864],
  ['2019-01-02',
   None,
   18919212000,
   39.48,
   37.58,
   39.71,
   38.56,
   38.72,
   148158948],
  ['2019-01-03',
   None,
   18919212000,
   35.55,
   33.83,
   36.43,
   35.5,
   35.99,
   365248780],
  ['2019-01-04',
   None,
   18919212000,
   37.06,
   35.28,
   37.14,
   35.95,
   36.13,
   234428280],
  ['2019-01-07',
   None,
   18919212000,
   36.98,
   35.2,
   37.21,
   36.48,
   37.17,
   219111056],
  ['2019-01-08',
   None,
   18919212000,
   37.69,
   35.87,
   37.95,
   37.13,
   37.39,
   164101256],
  ['2019-01-09',
   None,
   18919212000,
   38.33,
   36.48,
   38.63,
   37.41,
   37.82,
   180396324],
  ['2019-01-10',
   None,
   18919212000,
   38.45,
   36.6,
   38.49,
   37.72,
   38.12,
   143122680],
  ['2019-01-11',
   None,
   18919212000,
   38.07,
   36.24,
   38.42,
   37.88,
   38.22,
   108092964],
  ['2019-01-14',
   None,
   18919212000,
   37.5,
   35.69,
   37.82,
   37.3,
   37.71,
   129756744],
  ['2019-01-15',
   None,
   18919212000,
   38.27,
   36.42,
   38.35,
   37.51,
   37.57,
   114841296],
  ['2019-01-16',
   None,
   18919212000,
   38.73,
   36.87,
   38.97,
   38.25,
   38.27,
   122278824],
  ['2019-01-17',
   None,
   18919212000,
   38.97,
   37.09,
   39.41,
   38.31,
   38.55,
   119284640],
  ['2019-01-18',
   None,
   18861120000,
   39.2,
   37.32,
   39.47,
   38.99,
   39.38,
   135004092],
  ['2019-01-22',
   None,
   18861120000,
   38.33,
   36.48,
   39.18,
   38.16,
   39.1,
   121575880],
  ['2019-01-23',
   None,
   18861120000,
   38.48,
   36.62,
   38.78,
   37.92,
   38.54,
   92522280],
  ['2019-01-24',
   None,
   18861120000,
   38.17,
   36.33,
   38.62,
   37.94,
   38.53,
   101766196],
  ['2019-01-25',
   None,
   18861120000,
   39.44,
   37.54,
   39.53,
   38.58,
   38.87,
   134191572],
  ['2019-01-28',
   None,
   18861120000,
   39.08,
   37.19,
   39.08,
   38.41,
   38.95,
   104768232],
  ['2019-01-29',
   None,
   18861120000,
   38.67,
   36.81,
   39.53,
   38.53,
   39.06,
   166348956],
  ['2019-01-30',
   None,
   18861120000,
   41.31,
   39.32,
   41.54,
   40.06,
   40.81,
   244439120],
  ['2019-01-31',
   None,
   18861120000,
   41.61,
   39.6,
   42.25,
   41.14,
   41.53,
   162958596],
  ['2019-02-01',
   None,
   18861120000,
   41.63,
   39.62,
   42.24,
   41.48,
   41.74,
   130672552],
  ['2019-02-04',
   None,
   18861120000,
   42.81,
   40.75,
   42.91,
   41.82,
   41.85,
   125982328],
  ['2019-02-05',
   None,
   18861120000,
   43.55,
   41.45,
   43.77,
   43.09,
   43.22,
   144406512],
  ['2019-02-06',
   None,
   18861120000,
   43.56,
   41.46,
   43.89,
   43.21,
   43.66,
   112958364],
  ['2019-02-07',
   None,
   18861120000,
   42.73,
   40.67,
   43.48,
   42.59,
   43.1,
   126966760],
  ['2019-02-08', 0.18, 18861120000, 42.6, 40.72, 42.66, 42.1, 42.25, 95279864],
  ['2019-02-11',
   None,
   18861120000,
   42.36,
   40.49,
   42.8,
   42.31,
   42.76,
   83973700],
  ['2019-02-12',
   None,
   18861120000,
   42.72,
   40.84,
   42.75,
   42.42,
   42.52,
   89134092],
  ['2019-02-13',
   None,
   18861120000,
   42.55,
   40.67,
   43.12,
   42.48,
   42.85,
   89960932],
  ['2019-02-14',
   None,
   18861120000,
   42.7,
   40.82,
   42.81,
   42.34,
   42.43,
   87342988],
  ['2019-02-15',
   None,
   18861120000,
   42.6,
   40.72,
   42.92,
   42.44,
   42.81,
   98507256],
  ['2019-02-19',
   None,
   18861120000,
   42.73,
   40.85,
   42.86,
   42.37,
   42.43,
   75891304],
  ['2019-02-20',
   None,
   18861120000,
   43.01,
   41.11,
   43.33,
   42.75,
   42.8,
   104457448],
  ['2019-02-21',
   None,
   18861120000,
   42.77,
   40.88,
   43.09,
   42.58,
   42.95,
   68998680],
  ['2019-02-22',
   None,
   18861120000,
   43.24,
   41.33,
   43.25,
   42.84,
   42.9,
   75652616],
  ['2019-02-25',
   None,
   18861120000,
   43.56,
   41.64,
   43.97,
   43.49,
   43.54,
   87493432],
  ['2019-02-26',
   None,
   18861120000,
   43.58,
   41.66,
   43.83,
   43.29,
   43.43,
   68280844],
  ['2019-02-27',
   None,
   18861120000,
   43.72,
   41.79,
   43.75,
   43.18,
   43.3,
   111341556],
  ['2019-02-28',
   None,
   18861120000,
   43.29,
   41.38,
   43.73,
   43.23,
   43.58,
   112861664],
  ['2019-03-01',
   None,
   18861120000,
   43.74,
   41.81,
   43.79,
   43.22,
   43.57,
   103544668],
  ['2019-03-04',
   None,
   18861120000,
   43.96,
   42.02,
   44.44,
   43.49,
   43.92,
   109744812],
  ['2019-03-05',
   None,
   18861120000,
   43.88,
   41.95,
   44.0,
   43.63,
   43.98,
   78949676],
  ['2019-03-06',
   None,
   18861120000,
   43.63,
   41.7,
   43.87,
   43.48,
   43.67,
   83241536],
  ['2019-03-07',
   None,
   18861120000,
   43.12,
   41.22,
   43.61,
   43.01,
   43.47,
   99185496],
  ['2019-03-08',
   None,
   18861120000,
   43.23,
   41.32,
   43.27,
   42.38,
   42.58,
   95997432],
  ['2019-03-11',
   None,
   18861120000,
   44.73,
   42.75,
   44.78,
   43.84,
   43.87,
   128044136],
  ['2019-03-12',
   None,
   18861120000,
   45.23,
   43.23,
   45.67,
   44.84,
   45.0,
   129870336],
  ['2019-03-13',
   None,
   18861120000,
   45.43,
   43.42,
   45.83,
   45.23,
   45.56,
   124130096],
  ['2019-03-14',
   None,
   18861120000,
   45.93,
   43.91,
   46.02,
   45.64,
   45.98,
   94318032],
  ['2019-03-15',
   None,
   18861120000,
   46.53,
   44.48,
   46.83,
   45.94,
   46.21,
   156171648],
  ['2019-03-18',
   None,
   18861120000,
   47.01,
   44.93,
   47.1,
   46.45,
   46.45,
   104879328],
  ['2019-03-19',
   None,
   18861120000,
   46.63,
   44.57,
   47.25,
   46.48,
   47.09,
   126585476],
  ['2019-03-20',
   None,
   18861120000,
   47.04,
   44.96,
   47.37,
   46.18,
   46.56,
   124140924],
  ['2019-03-21',
   None,
   18861120000,
   48.77,
   46.62,
   49.08,
   47.45,
   47.51,
   204136948],
  ['2019-03-22',
   None,
   18861120000,
   47.76,
   45.65,
   49.42,
   47.7,
   48.84,
   169630664],
  ['2019-03-25',
   None,
   18861120000,
   47.19,
   45.1,
   47.99,
   46.65,
   47.88,
   175381172],
  ['2019-03-26',
   None,
   18861120000,
   46.7,
   44.64,
   48.22,
   46.15,
   47.91,
   199202152],
  ['2019-03-27',
   None,
   18861120000,
   47.12,
   45.04,
   47.44,
   46.64,
   47.19,
   119393708],
  ['2019-03-28',
   None,
   18861120000,
   47.18,
   45.1,
   47.39,
   46.88,
   47.24,
   83121452],
  ['2019-03-29',
   None,
   18861120000,
   47.49,
   45.39,
   47.52,
   47.13,
   47.46,
   94255844],
  ['2019-04-01',
   None,
   18429136000,
   47.81,
   45.7,
   47.92,
   47.09,
   47.91,
   111447856],
  ['2019-04-02',
   None,
   18429136000,
   48.51,
   46.36,
   48.62,
   47.76,
   47.77,
   91062928],
  ['2019-04-03',
   None,
   18429136000,
   48.84,
   46.68,
   49.12,
   48.29,
   48.31,
   93087320],
  ['2019-04-04',
   None,
   18429136000,
   48.92,
   46.76,
   49.09,
   48.28,
   48.7,
   76457100],
  ['2019-04-05',
   None,
   18429136000,
   49.25,
   47.08,
   49.27,
   48.98,
   49.11,
   74106576],
  ['2019-04-08',
   None,
   18429136000,
   50.02,
   47.82,
   50.06,
   49.09,
   49.1,
   103526788],
  ['2019-04-09',
   None,
   18429136000,
   49.88,
   47.67,
   50.71,
   49.81,
   50.08,
   143072948],
  ['2019-04-10',
   None,
   18429136000,
   50.16,
   47.94,
   50.19,
   49.55,
   49.67,
   86781152],
  ['2019-04-11',
   None,
   18429136000,
   49.74,
   47.54,
   50.25,
   49.61,
   50.21,
   83603232],
  ['2019-04-12',
   None,
   18429136000,
   49.72,
   47.52,
   50.03,
   49.05,
   49.8,
   111042672],
  ['2019-04-15',
   None,
   18429136000,
   49.81,
   47.61,
   49.96,
   49.5,
   49.65,
   70146584],
  ['2019-04-16',
   None,
   18429136000,
   49.81,
   47.61,
   50.34,
   49.64,
   49.87,
   102785540],
  ['2019-04-17',
   None,
   18429136000,
   50.78,
   48.54,
   50.84,
   49.65,
   49.88,
   115627120],
  ['2019-04-18',
   None,
   18429136000,
   50.97,
   48.72,
   51.04,
   50.63,
   50.78,
   96783064],
  ['2019-04-22',
   None,
   18404300000,
   51.13,
   48.88,
   51.23,
   50.59,
   50.71,
   77758180],
  ['2019-04-23',
   None,
   18404300000,
   51.87,
   49.58,
   51.94,
   50.98,
   51.11,
   93291964],
  ['2019-04-24',
   None,
   18404300000,
   51.79,
   49.5,
   52.12,
   51.76,
   51.84,
   70162436],
  ['2019-04-25',
   None,
   18404300000,
   51.32,
   49.06,
   51.94,
   51.28,
   51.71,
   74172824],
  ['2019-04-26',
   None,
   18404300000,
   51.08,
   48.82,
   51.25,
   50.53,
   51.23,
   74596408],
  ['2019-04-29', None, 18404300000, 51.15, 48.9, 51.49, 50.97, 51.1, 88818864],
  ['2019-04-30',
   None,
   18404300000,
   50.17,
   47.95,
   50.85,
   49.78,
   50.77,
   186139692],
  ['2019-05-01',
   None,
   18404300000,
   52.63,
   50.31,
   53.83,
   52.31,
   52.47,
   259309312],
  ['2019-05-02',
   None,
   18404300000,
   52.29,
   49.98,
   53.16,
   52.03,
   52.46,
   127985296],
  ['2019-05-03',
   None,
   18404300000,
   52.94,
   50.6,
   52.96,
   52.56,
   52.72,
   83569512],
  ['2019-05-06',
   None,
   18404300000,
   52.12,
   49.82,
   52.21,
   50.88,
   51.07,
   129772452],
  ['2019-05-07',
   None,
   18404300000,
   50.72,
   48.48,
   51.85,
   50.21,
   51.47,
   155054792],
  ['2019-05-08',
   None,
   18404300000,
   50.73,
   48.49,
   51.34,
   50.44,
   50.48,
   105358016],
  ['2019-05-09',
   None,
   18404300000,
   50.18,
   47.97,
   50.42,
   49.16,
   50.1,
   139634428],
  ['2019-05-10',
   0.19,
   18404300000,
   49.3,
   47.3,
   49.71,
   48.19,
   49.35,
   164834848],
  ['2019-05-13',
   None,
   18404300000,
   46.43,
   44.55,
   47.37,
   45.71,
   46.93,
   229722492],
  ['2019-05-14',
   None,
   18404300000,
   47.16,
   45.26,
   47.42,
   46.35,
   46.6,
   146118708],
  ['2019-05-15',
   None,
   18404300000,
   47.73,
   45.8,
   47.94,
   46.51,
   46.57,
   106178872],
  ['2019-05-16',
   None,
   18404300000,
   47.52,
   45.6,
   48.12,
   47.21,
   47.48,
   132125456],
  ['2019-05-17',
   None,
   18404300000,
   47.25,
   45.34,
   47.73,
   46.69,
   46.73,
   131516360],
  ['2019-05-20',
   None,
   18404300000,
   45.77,
   43.92,
   46.09,
   45.07,
   45.88,
   154449160],
  ['2019-05-21',
   None,
   18404300000,
   46.65,
   44.77,
   47.0,
   46.17,
   46.3,
   113459392],
  ['2019-05-22',
   None,
   18404300000,
   45.7,
   43.85,
   46.43,
   45.64,
   46.16,
   118994224],
  ['2019-05-23',
   None,
   18404300000,
   44.91,
   43.1,
   45.13,
   44.45,
   44.95,
   146118944],
  ['2019-05-24',
   None,
   18404300000,
   44.74,
   42.93,
   45.53,
   44.66,
   45.05,
   94858744],
  ['2019-05-28',
   None,
   18404300000,
   44.56,
   42.76,
   45.15,
   44.48,
   44.73,
   111792640],
  ['2019-05-29',
   None,
   18404300000,
   44.34,
   42.55,
   44.84,
   44.0,
   44.1,
   113924660],
  ['2019-05-30',
   None,
   18404300000,
   44.58,
   42.77,
   44.81,
   44.17,
   44.49,
   84873648],
  ['2019-05-31',
   None,
   18404300000,
   43.77,
   42.0,
   44.5,
   43.75,
   44.06,
   108174336],
  ['2019-06-03',
   None,
   18404300000,
   43.33,
   41.57,
   44.48,
   42.57,
   43.9,
   161584276],
  ['2019-06-04',
   None,
   18404300000,
   44.91,
   43.1,
   44.96,
   43.63,
   43.86,
   123871844],
  ['2019-06-05',
   None,
   18404300000,
   45.63,
   43.79,
   46.25,
   45.28,
   46.07,
   119093708],
  ['2019-06-06',
   None,
   18404300000,
   46.3,
   44.43,
   46.37,
   45.54,
   45.77,
   90105244],
  ['2019-06-07',
   None,
   18404300000,
   47.54,
   45.62,
   47.98,
   46.44,
   46.63,
   122737572],
  ['2019-06-10',
   None,
   18404300000,
   48.15,
   46.2,
   48.84,
   47.91,
   47.95,
   104883404],
  ['2019-06-11', None, 18404300000, 48.7, 46.74, 49.0, 48.4, 48.72, 107731528],
  ['2019-06-12',
   None,
   18404300000,
   48.55,
   46.59,
   48.99,
   48.35,
   48.49,
   73012756],
  ['2019-06-13', None, 18404300000, 48.54, 46.58, 49.2, 48.4, 48.67, 86698500],
  ['2019-06-14',
   None,
   18404300000,
   48.19,
   46.24,
   48.4,
   47.58,
   47.89,
   75045896],
  ['2019-06-17',
   None,
   18404300000,
   48.47,
   46.51,
   48.74,
   48.04,
   48.23,
   58676576],
  ['2019-06-18',
   None,
   18404300000,
   49.61,
   47.61,
   50.07,
   48.8,
   49.01,
   106204016],
  ['2019-06-19',
   None,
   18404300000,
   49.47,
   47.47,
   49.97,
   49.33,
   49.92,
   84496940],
  ['2019-06-20',
   None,
   18404300000,
   49.87,
   47.85,
   50.15,
   49.51,
   50.09,
   86055952],
  ['2019-06-21',
   None,
   18404300000,
   49.7,
   47.69,
   50.21,
   49.54,
   49.7,
   191202356],
  ['2019-06-24',
   None,
   18404300000,
   49.65,
   47.64,
   50.04,
   49.54,
   49.63,
   72881684],
  ['2019-06-25',
   None,
   18404300000,
   48.89,
   46.92,
   49.81,
   48.82,
   49.61,
   84281336],
  ['2019-06-26',
   None,
   18404300000,
   49.95,
   47.93,
   50.25,
   49.34,
   49.44,
   104270048],
  ['2019-06-27',
   None,
   18404300000,
   49.94,
   47.92,
   50.39,
   49.89,
   50.07,
   83598868],
  ['2019-06-28',
   None,
   18404300000,
   49.48,
   47.48,
   49.88,
   49.26,
   49.67,
   124442568],
  ['2019-07-01',
   None,
   18125580000,
   50.39,
   48.35,
   51.12,
   50.16,
   50.79,
   109266956],
  ['2019-07-02',
   None,
   18125580000,
   50.68,
   48.64,
   50.78,
   50.34,
   50.35,
   67740868],
  ['2019-07-03',
   None,
   18125580000,
   51.1,
   49.04,
   51.11,
   50.67,
   50.82,
   45448180],
  ['2019-07-05',
   None,
   18125580000,
   51.06,
   48.99,
   51.27,
   50.73,
   50.84,
   69062072],
  ['2019-07-08',
   None,
   18125580000,
   50.01,
   47.98,
   50.35,
   49.6,
   50.2,
   101354512],
  ['2019-07-09', None, 18125580000, 50.31, 48.28, 50.38, 49.7, 49.8, 82312060],
  ['2019-07-10',
   None,
   18125580000,
   50.81,
   48.75,
   50.93,
   50.39,
   50.46,
   71588552],
  ['2019-07-11', None, 18125580000, 50.44, 48.4, 51.1, 50.43, 50.83, 80767368],
  ['2019-07-12',
   None,
   18125580000,
   50.83,
   48.77,
   51.0,
   50.55,
   50.61,
   70380848],
  ['2019-07-15', None, 18125580000, 51.3, 49.23, 51.47, 51.0, 51.02, 67789680],
  ['2019-07-16',
   None,
   18125580000,
   51.12,
   49.06,
   51.53,
   50.88,
   51.15,
   67467264],
  ['2019-07-17',
   None,
   18125580000,
   50.84,
   48.78,
   51.27,
   50.82,
   51.01,
   56429800],
  ['2019-07-18',
   None,
   18125580000,
   51.41,
   49.34,
   51.47,
   50.92,
   51.0,
   74328644],
  ['2019-07-19',
   None,
   18076720000,
   50.65,
   48.6,
   51.62,
   50.59,
   51.45,
   83717228],
  ['2019-07-22', None, 18076720000, 51.8, 49.71, 51.81, 50.9, 50.91, 89111728],
  ['2019-07-23',
   None,
   18076720000,
   52.21,
   50.1,
   52.23,
   51.82,
   52.12,
   73420840],
  ['2019-07-24',
   None,
   18076720000,
   52.17,
   50.06,
   52.29,
   51.79,
   51.92,
   59966268],
  ['2019-07-25',
   None,
   18076720000,
   51.76,
   49.66,
   52.31,
   51.68,
   52.22,
   55638140],
  ['2019-07-26',
   None,
   18076720000,
   51.94,
   49.84,
   52.43,
   51.78,
   51.87,
   70475496],
  ['2019-07-29',
   None,
   18076720000,
   52.42,
   50.3,
   52.66,
   52.11,
   52.12,
   86693556],
  ['2019-07-30',
   None,
   18076720000,
   52.2,
   50.09,
   52.54,
   51.83,
   52.19,
   135742872],
  ['2019-07-31',
   None,
   18076720000,
   53.26,
   51.11,
   55.34,
   52.83,
   54.1,
   277125444],
  ['2019-08-01',
   None,
   18076720000,
   52.11,
   50.0,
   54.51,
   51.69,
   53.48,
   216071688],
  ['2019-08-02',
   None,
   18076720000,
   51.01,
   48.94,
   51.61,
   50.41,
   51.38,
   163448488],
  ['2019-08-05',
   None,
   18076720000,
   48.34,
   46.38,
   49.66,
   48.15,
   49.5,
   209571876],
  ['2019-08-06',
   None,
   18076720000,
   49.25,
   47.26,
   49.52,
   48.51,
   49.08,
   143299148],
  ['2019-08-07',
   None,
   18076720000,
   49.76,
   47.75,
   49.89,
   48.45,
   48.85,
   133457600],
  ['2019-08-08',
   None,
   18076720000,
   50.86,
   48.8,
   50.88,
   49.85,
   50.05,
   108038092],
  ['2019-08-09',
   0.19,

Testing out more parameters

In [24]:
endpoint_url= f"{base_url}/prices/compact"

params = {'ticker': 'NVDA',
          'start':'2025-10-20'}

price_data_response = requests.get(endpoint_url, headers=headers, params=params)

if price_data_response.status_code == 200:
    # Parse the JSON response
    price_data = price_data_response.json()
else:
    print(f"Failed to retrieve data. Status code: {price_data_response.status_code}")

In [25]:
price_data

[{'columns': ['Date',
   'Dividend Paid',
   'Common Shares Outstanding',
   'Last Closing Price',
   'Adjusted Closing Price',
   'Highest Price',
   'Lowest Price',
   'Opening Price',
   'Trading Volume'],
  'name': 'NVIDIA CORP',
  'id': 172199,
  'ticker': 'NVDA',
  'currency': 'USD',
  'isin': 'US67066G1040',
  'data': [['2025-10-20',
    None,
    24300000000,
    182.64,
    182.64,
    185.2,
    181.73,
    183.13,
    127536141],
   ['2025-10-21',
    None,
    24300000000,
    181.16,
    181.16,
    182.78,
    179.8,
    182.78,
    118981172],
   ['2025-10-22',
    None,
    24300000000,
    180.28,
    180.28,
    183.44,
    176.76,
    181.14,
    161195656],
   ['2025-10-23',
    None,
    24300000000,
    182.16,
    182.16,
    183.03,
    179.79,
    180.42,
    110031592],
   ['2025-10-24',
    None,
    24300000000,
    186.26,
    186.26,
    187.47,
    183.5,
    183.84,
    130388594],
   ['2025-10-27',
    None,
    24300000000,
    191.49,
    191.49,
    192.0,
    188.43,
    189.99,
    150598129],
   ['2025-10-28',
    None,
    24300000000,
    201.03,
    201.03,
    203.15,
    191.91,
    193.05,
    289125859],
   ['2025-10-29',
    None,
    24300000000,
    207.04,
    207.04,
    212.19,
    204.78,
    207.98,
    304583919],
   ['2025-10-30',
    None,
    24300000000,
    202.89,
    202.89,
    206.16,
    201.41,
    205.15,
    175023079],
   ['2025-10-31',
    None,
    24300000000,
    202.49,
    202.49,
    207.97,
    202.07,
    206.45,
    178199381],
   ['2025-11-03',
    None,
    24300000000,
    206.88,
    206.88,
    211.34,
    205.56,
    208.08,
    177511177],
   ['2025-11-04',
    None,
    24300000000,
    198.69,
    198.69,
    203.97,
    197.93,
    203.0,
    184656303],
   ['2025-11-05',
    None,
    24300000000,
    195.21,
    195.21,
    202.92,
    194.65,
    198.77,
    166849081],
   ['2025-11-06',
    None,
    24300000000,
    188.08,
    188.08,
    197.62,
    186.38,
    196.42,
    220032907],
   ['2025-11-07',
    None,
    24300000000,
    188.15,
    188.15,
    188.32,
    178.91,
    184.9,
    262255193]]}]

In [26]:
len(price_data)

1

Getting share price for top 40 companies

In [27]:
for company in top_50_companies:
    ticker = company['ticker']
    params = {'ticker': f'{ticker}',
          'start':'2025-10-20'}

    price_data_response = requests.get(endpoint_url, headers=headers, params=params)

    if price_data_response.status_code == 200:
        # Parse the JSON response
        price_data = price_data_response.json()
    else:
        print(f"Failed to retrieve data. Status code: {price_data_response.status_code}")

Failed to retrieve data. Status code: 429
Failed to retrieve data. Status code: 429
Failed to retrieve data. Status code: 429
Failed to retrieve data. Status code: 429
Failed to retrieve data. Status code: 429
Failed to retrieve data. Status code: 429

KeyboardInterrupt:

In [ ]:
len(price_data)

In [ ]:
price_data

## Exploration

In [28]:
import pandas as pd

In [29]:
#Creates the columns for the DF --> WORKS
dict_data = price_data[0]
columns = ['name', 'ticker', 'currency']
info = dict_data['columns']
columns.extend(info)
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [name, ticker, currency, Date, Dividend Paid, Common Shares Outstanding, Last Closing Price, Adjusted Closing Price, Highest Price, Lowest Price, Opening Price, Trading Volume]
Index: []

In [ ]:
#creating the function --> works
def creating_columns(price_data: list):
    dict_data = price_data[0]
    columns = ['name', 'ticker', 'currency']
    info = dict_data['columns']
    columns.extend(info)
    df = pd.DataFrame(columns=columns)
    return df

In [ ]:
#This function is definite. it works well

def transformations(price_data: list):
    #creates columns
    dict_data = price_data[0]
    columns = ['name', 'ticker', 'currency']
    info = dict_data['columns']
    columns.extend(info)
    df = pd.DataFrame(columns=columns)
    
    #Appends the data as rows to the DF
    for i in price_data:
        data = [i['name'], i['ticker'], i['currency']]
        stock_data = i['data'][0]
        data.extend(stock_data)
        df.loc[len(df)] = data

    return df

In [ ]:
transformations(price_data)

In [ ]:
#testing the function --> works
creating_columns(price_data)

In [ ]:
#Appends the data as rows to the df --> WORKS
for i in price_data:
    data = [i['name'], i['ticker'], i['currency']]
    stock_data = i['data'][0]
    data.extend(stock_data)
    df.loc[len(df)] = data

df

In [ ]:
price_data[0]

In [ ]:
#creating the function
def append_data(price_data:list):
    creating_columns(price_data)
    for i in price_data:
        data = [i['name'], i['ticker'], i['currency']]
        stock_data = i['data'][0]
        data.extend(stock_data)
        df.loc[len(df)] = data
    return df

In [ ]:
append_data(price_data)

NEED TO BE ABLE TO ITERATE OVER ALL TICKERS

In [ ]:
DO DATA CHECKS ON DATE (EG MUST ALWAYS BE THE SAME, ETC.)

---

Getting todays date --> for automating api call...

In [ ]:
import datetime

In [ ]:
datetime.datetime.today()

In [ ]:
str(datetime.datetime.today())

In [ ]:
str(datetime.datetime.today()).split()

In [ ]:
str(datetime.datetime.today()).split()[0]

## Creating the API wrapper
I need to study OOP --> will help me with this

In [ ]:
import pprint

In [ ]:
endpoint_url = "https://backend.simfin.com/api/v3/companies/prices/compact"


headers = {"accept": "application/json",
            "Authorization": f"{API_KEY}"}

In [ ]:
endpoint_url= f"{base_url}/prices/compact"

params = {'ticker': 'AAPL, STL'}

price_data_response = requests.get(endpoint_url, headers=headers, params=params)

if price_data_response.status_code == 200:
    # Parse the JSON response
    price_data = price_data_response.json()
else:
    print(f"Failed to retrieve data. Status code: {price_data_response.status_code}")

In [ ]:
endpoint_url = "https://backend.simfin.com/api/v3/companies/prices/compact"


headers = {"accept": "application/json",
            "Authorization": f"{API_KEY}"}

In [ ]:
## This whole block works
class PySimFin:
    def __init__(self):
        self.endpoint_url = "https://backend.simfin.com/api/v3/companies/prices/compact"
        self.headers = {"accept": "application/json", "Authorization": f"{API_KEY}"}   

    def get_share_prices(self, ticker: str):
        params = {'ticker': ticker}
        response = requests.get(self.endpoint_url, headers=self.headers, params=params)
        if response.status_code == 200:
            data = response.json()
            print(data)
        else:
            print(f"Failed to retrieve data. Status code: {response.status_code}")

In [ ]:
## This whole block works --> better. Avoids hardcoding.
class PySimFin1:
    def __init__(self):
        self.endpoint_url = f"{endpoint_url}"
        self.headers = headers.copy()   

    def get_share_prices(self, ticker: str):
        params = {'ticker': ticker}
        response = requests.get(self.endpoint_url, headers=self.headers, params=params)
        if response.status_code == 200:
            data = response.json()
            print(data)
        else:
            print(f"Failed to retrieve data. Status code: {response.status_code}")

In [ ]:
easy = PySimFin1()

In [ ]:
easy.get_share_prices('AAPL')

Trying to get the value just for today

In [ ]:
class PySimFin1:
    def __init__(self):
        self.endpoint_url = f"{endpoint_url}"
        self.headers = headers.copy()   

    def get_share_prices(self, ticker: str):
        params = {'ticker': ticker}
        response = requests.get(self.endpoint_url, headers=self.headers, params=params)
        if response.status_code == 200:
            data = response.json()
            print(data)
        else:
            print(f"Failed to retrieve data. Status code: {response.status_code}")


    def get_share_prices_today(self, ticker: str):
        today = str(datetime.datetime.today()).split()[0] #gets today's date
        params = {'ticker': ticker,
                  'start': today}
        response = requests.get(self.endpoint_url, headers=self.headers, params=params)
        if response.status_code == 200:
            data = response.json()
            print(data)
        else:
            print(f"Failed to retrieve data. Status code: {response.status_code}")

In [ ]:
dsjks = PySimFin1()

In [ ]:
dsjks.get_share_prices_today('STL')